### ISSUE TITLE
readAnnotationCas should create CAS for the current user

### ISSUE THREAD

**Issue by Rentier** [webanno/webanno#1024]
If an `AnnotationDocument` does not have corresponding CAS when calling `readAnnotationCas`, it creates a new CAS for the owner of the document. Instead, it should create a CAS for the current user.

**Comment by reckart** [comment]
That method must retrieve the user from the `AnnotationDocument` that is passed as an argument. Changing it to retrieve the current user from the security context instead would most likely break all kinds of things and it would also be very surprising. If you need control over the user for which the CAS is returned, there is the deprecated`readAnnotationCas(SourceDocument aDocument, User aUser)`, but it should be avoided because of its side effects. If necessary, a new method like `readAnnotationCas(SourceDocument aDocument, String aUser)` could be introduced.
