### ISSUE TITLE
Display error with v3.2.4

### ISSUE THREAD

**Issue by SJones-Appen** [webanno/webanno#1042]
Greetings colleagues -
[display_3.2.4.zip](https://github.com/webanno/webanno/files/2368595/display_3.2.4.zip)
I'm having trouble getting a file to display correctly. I've attached the file, the layer, and the tagset.
When I first uploaded the file, the first sentence was only partially visible, and I was unable to see the first several lines. I duplicated the first entry and uploaded it again. This time the display problem persisted, but I was able to apply an annotation on the second instance of the first sentence. However, when I applied the first annotation tag, the display vanished entirely. If possible please investigate and help me find the problem.
THANK YOU!!

**Comment by reckart** [comment]
Which version of WebAnno are you using?

**Comment by SJones-Appen** [comment]
v3.2.4

**Comment by reckart** [comment]
That version is quite ancient. Could you try to check if the problem persists with the latest WebAnno version?

**Comment by reckart** [comment]
If you create the TSV files outside of WebAnno and then try to import them, please observe how offsets of multi-byte characters are treated by WebAnno: https://webanno.github.io/webanno/releases/3.4.5/docs/user-guide.html#_encoding_and_offsets

**Comment by SJones-Appen** [comment]
The problem does persist in standalone v3.4.5. It displays all three sentences correctly. However, as soon as I apply a tag, the display of the sentences vanishes entirely.
For some time I have been preparing files (I have many) in WA v2 and importing them using that format into WA3, to save time by letting the tool set the character offsets.

**Comment by reckart** [comment]
I imported the data into my local WebAnno 3.5.0-SNAPSHOT build and accessed the application using Safari 11.1.2 .There, I couldn't reproduce the problem that the sentences disappeared entirely. However, I could notice that something was strange: if I created a token annotation one any of the first 15-20 tokens, the annotation would be rendered as a zero-span annotation at the beginning of the token instead of as a full-token annotation. I could verify though that the annotation was internally correctly created. In an XMI export, I noticed that between many words in the first sentence, there were two spaces instead of one. Since TSV2 doesn't have offsets and tokens are not allowed to contain spaces in WebAnno, there should be only a single space. Inspecting the TSV2 file you submitted, I noticed that some lines contain a trailing space character after the token. Removing that trailing space character in a text editor and then importing the file again seems to resolve all problems.

Can you please check the code that you use to generate these files and ensure that it doesn't add leading or trailing whitespace in any of the columns?

**Comment by SJones-Appen** [comment]
I have added the same comment twice now (confirming your fix and thanking for help), they aren't being saved.

**Comment by reckart** [comment]
Glad that it worked now :)
