### ISSUE TITLE
Unable to import projects/layers exported from older Webanno versions

### ISSUE THREAD

**Issue by Tiberiu17** [webanno/webanno#1063]
Hi,

I have a standalone version of 3.5.0 beta-4 version of Webanno installed. I tried to import projects exported as UIMA BIN from a 3.2.4 server version and also as TSV3 from a 3.4.5 standalone version, which both failed.
The error given is this one: Error importing project: UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only.

An error also occurred when I tried to import a layer exported from the 3.2.4 version.
The error sounded like this: 

> Error importing layers: MismatchedInputException: Cannot deserialize instance of `de.tudarmstadt.ukp.clarin.webanno.export.model.ExportedAnnotationLayer[]` out of START_OBJECT token at [Source: (String)"{ "name" : "webanno.custom.People", "features" : [ { "name" : "value", "tag_set" : { "name" : "People_PG", "typeUiName" : null, "description" : null, "language" : null, "type" : null, "type_name" : null, "type_description" : null, "tags" : [ { "tag_name" : "PG_Age", "tag_description" : "Only annotate sentence-like contexts" }, { "tag_name" : "PG_Age_Years_Old", "tag_description" : "Only annotate sen"[truncated 2411 chars]; line: 1, column: 1]

Can these compatibility issues be solved in any way?

Thank you.

Best,
Tiberiu

**Comment by reckart** [comment]
I'll have a look if I can reproduce this locally.

**Comment by reckart** [comment]
I opened a new issue for the problem that projects cannot be imported:

https://github.com/webanno/webanno/pull/1072

Regarding the import of layers: you can manually add a `[` and `]` to the beginning and end of the JSON file - that should fix the issue. 

I'm not sure if it is worth making this backwards compatible. Since a while, WebAnno expects the exported layers file to be a list of layers, not just a single layer object. This change was a minor side-effect of consolidating some code in the backend. I'd tend to just leave it the way it is.

**Comment by Tiberiu17** [comment]
Thank you. The [ ] addition did the trick.

I have noticed the same issue with importing these projects in Inception too. Should I create a ticket for it or it will be taken care of?

Best,
Tiberiu

**Comment by reckart** [comment]
@Tiberiu17 INCEpTION profits from the fix here. No extra ticket required.
