### ISSUE TITLE
Finishing takes forever in annotation/curation for certain documents

### ISSUE THREAD

**Issue by rgsol** [webanno/webanno#1205]
**Describe the bug**
If you click "finish" and confirm then for certain documents the interface never comes back. You'll see the spinner until you get logged out after 30 minutes. No error messages occur. 

**To Reproduce**
I have prepared an example project but get an error message if I try to attach it:

_Something went really wrong, and we can't process that file_
 
May be it's the size: it's 18M. The document in question is itself 29M.

**Expected behavior**
Expected to finish without error in less than 30 minutes.

**Screenshots**

**Please complete the following information:**
 - Version and build ID:  WebAnno -- 3.5.1 (2019-01-24 16:31:23, build 8af8380d51efac0dc8f68720373eeaf0acc21344) 
 - OS: Linux (Debian)
 - Browser: Firefox, Chromium

**Additional context**
Might be connected to changes introduced after: https://github.com/webanno/webanno/issues/1196
In version 3.4.8 (2019-01-12 18:03:11, build a56b52716a6b169c79fa8e2a607cd1a2a9685b6e) finishing works for the example project.

**Comment by reckart** [comment]
It is possible/probable that the new validation of the correctness of the annotations takes too long. I guess I will make that optional so that managers of projects which large documents can turn validation off. You could e.g. put the project to Google Drive / Dropbox and post a link here - or send it to me by mail.

**Comment by rgsol** [comment]
Didn't use Google Drive for a long time ;-)
 
https://drive.google.com/file/d/1eaMPxLPODglyp9BY6NU-cBtsJD6Wk2kp/view?usp=sharing

**Comment by reckart** [comment]
I can see there is a performance problem in the validation of sentence crossing:

```
....
	JCasUtil.selectCovering(JCas, Class<T>, int, int) line: 474	
	WebAnnoCasUtil.isBeginEndInSameSentence(JCas, int, int) line: 128	
	SpanCrossSentenceBehavior.onValidate(TypeAdapter, JCas) line: 110	
	SpanAdapter.validate(JCas) line: 163	
	AnnotationPage(AnnotationPageBase).actionValidateDocument(AjaxRequestTarget, JCas) line: 404	
....																																																																																																													
```

There might be other validators with performance issues as well. Unfortunately, this check is currently applied even to the Token layer which means there is no way of circumventing it by normal means because the Token layer settings are not accessible via the UI. The only way would be to go directly into the DB and change the  `crossSentence` column for layers with many annotations (e.g. Token) from `0` to `1`.

I'll look into it ASAP. Thanks for the report!
