### ISSUE TITLE
Annotation Editor action commands location

### ISSUE THREAD

**Issue by wpmp** [webanno/webanno#1210]
**Describe the refactoring action**
Currently the action commands (for example `spanOpenDialog`) used in the brat editor are located in the `de/tudarmstadt/ukp/clarin/webanno/brat/message` package in the response classes within brat module.
Those commands should probably be moved to api-annotation module.

**Expected benefit**
Better decoupling, helpful for implementing other editors beside brat.

**Comment by reckart** [comment]
I think what we need to do is to decouple the commands used by the editor from commands used in the backend - that seems to me to be the only reasonable way of supporting different editors.

So instead of moving the existing commands to the `api-annotation` module, we should introduce a new set of backend commands and map the editor commands to these backend commands. This is similar to the kind of decoupling we did with the `VDocument` (which is backend and editor-agnostic) and the `GetDocumentResponse` which is part of the brat-specific frontend code.

**Comment by reckart** [comment]
We'll do this if it crops up again as part of another refactoring but not address it as a major task on its own. Thus closing.
