### ISSUE TITLE
Optionally hide unconstraint features

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#130]
Add a behavior option to features that allows them to be displayed in the annotation detail editor panel only if they are covered by constraints rules (case 3 in #46).

* [x] option in feature editor in project settings
* [x] read/store setting during project import/export
* [x] make annotation detail editor panel aware of the option

**Comment by aakashysharma** [comment]
@reckart 
So, if I'm understanding you correctly, you require an option here (marked by yellow) in figure below
![130](https://cloud.githubusercontent.com/assets/1897100/10566920/9b99e778-75f4-11e5-9f6a-544ba01551c2.PNG)

Based on whether this is selected or not, what do you mean by "allows them to be displayed in the annotation detail editor panel "? e.g. this option is selected for aFrame, what will happen in that case?
Would the aFrame be hidden in AnnotationDEPanel if it's not "Green" status?

**Comment by aakashysharma** [comment]
Isn't behavior Layer-specific not Feature-specific?

**Comment by reckart** [comment]
Constraints affect individual features in a layer just as the cases specified in #46 are on a per-feature basis. So this should be a per-feature setting, not a per-layer setting. 

> e.g. this option is selected for aFrame, what will happen in that case?
Would the aFrame be hidden in AnnotationDEPanel if it's not "Green" status?

Yes.

**Comment by aakashysharma** [comment]
So the location of this option should be on bottom right side in "feature" settings (Above the dropdown where you select tagset for a feature?

Also, if enabled, we would be prohibiting any chances of making status "green". Is that the purpose? For example, if there are some rules for aFrame which have status "orange" because lemma value isn't matching. However, because of aFrame value, RoleSet values aren't exactly "green" and hence RoleSet is hidden.

Now you cannot show RoleSet unless you select proper value for aFrame. For that you'll need to disable this feature first in settings. Wouldn't that be cumbersome?

**Comment by reckart** [comment]
The RoleSet/Frame example is not working well here, but I give you another one:

Let's say we have features "POS", "case" and "person".

If POS is "verb", then "person" should be visible and the selectable values should be "1", "2" and "3".
If POS is "noun", then "case" should be visible and the selectable values should be "nominative", "genitive", etc.

**Comment by aakashysharma** [comment]
So, ideally it should only affect TextFeatureEditor and LinkFeatureEditor?

**Comment by reckart** [comment]
Yes - do you see any other places this could potentially affect?

**Comment by aakashysharma** [comment]
No, as those are the only places constraints affect as of now.
