### ISSUE TITLE
Improve UI for full sentence annotation

### ISSUE THREAD

**Issue by cif2cif** [webanno/webanno#140]
Currently you need to select the text and then annotate. 

We are annotating corpora and annotating the sentiment of each sentence.
It would be easier to have a kind of combo after each sentence and select a value (e.g. positive and negative). Now it takes several interactions.

Thanks.

**Comment by reckart** [comment]
What version of WebAnno are you using?

**Comment by seyyaw** [comment]
may be you can use the empty string annotation, but in WebAnno3. @ChrisBieTUDA

**Comment by reckart** [comment]
Btw. I think that a triple click should select a whole sentence. I read that brat has that functionality and I think we should have inherited that.

**Comment by cif2cif** [comment]
Sorry, I miss these messages.  Thanks for your answers. 

We are using the version 2.1.0.

**Comment by reckart** [comment]
In 3.3.0-SNAPSHOT (2017-08-06 19:52:54, build faf9115d794705e9104aef5172aa5c1e7c35024e), a triple-click does **not** create a full-sentence annotation.

**Comment by reckart** [comment]
INCEpTION supports sentence-level granularity. If you configure a layer for sentence-level granularity, the entire sentence is annotated, even if you mark only a word or character inside it. That may not yet be as convenient as having a dropdown next to every sentence, but it is pretty good. In particular because the annotation layer may have more than one feature and then the controls that would need to be shown next to each sentence may become arbitrarily complex.
