### ISSUE TITLE
Span annotation cannot be followed by a colon

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#156]
It is not possible to highlight a token followed by a colon without extending the span to both the colon and the following token. 
E.g.: Instead of "König" [: Was wünschen Sie?], WebAnno highlights "König: Was"

**Comment by reckart** [comment]
Which WebAnno version are you using?

Which behaviors are enabled for the layer? In particular, is "lock to token" or "lock to multiple tokens" enabled?

Can you export the annotation to TSV format and paste the relevant sentence here?

**Comment by sholschneider** [comment]
I am using WebAnno version 3.0.0-SNAPSHOT (2015-09-28 16:45:40, build d27759e452b7cdb7b79cfbbae5bc5f2f0661465e). "Allow crossing sentence boundary" and "allow multiple tokens" are enabled, "Read-only", "Lock to token offsets" and "Allow stacking" are not. An example is given in the screenshot below (TSV export). 
![colon2](https://cloud.githubusercontent.com/assets/13764947/11324995/2b657bb6-9142-11e5-8117-ff7211d2f236.PNG)

**Comment by reckart** [comment]
This might be a tokenization problem. Please note that the TSV screenshot does not match the example you gave initially.

As can been seen in the TSV screenshot above, we have two tokens `König:` and `habe`. If **lock to multiple tokens** is enabled and you select `: habe`, then WebAnno will automatically expand the selection to `König: habe` because the colon is part of the `König:` token. If you highlight `König`, then the selection should be automatically expanded to the full token `König:`.

There is a known problem with the logic that takes care of selection expansion in `Lock to token` and `Lock to multiple tokens`mode - this issue might be a variation of #154.

We should have automatic unit test for the expansion code.

**Comment by reckart** [comment]
Imported this as a plain text file:

```
König: Was wünschen Sie?
```

I use Safari 10.0.1 for the annotation.

Here I can make a POS annotation just over `König` and character-based annotations on arbitarary locations including/excluding the colon. Cannot reproduce problem.

WebAnno -- 3.0.0-SNAPSHOT (2016-12-05 20:57:52, build a3582fdec85645161196d86fe23209c1619275a9)
