### ISSUE TITLE
Remote Access in Standalone webanno

### ISSUE THREAD

**Issue by Kcanady1** [webanno/webanno#1699]
Is there any way to access the standalone version of webanno from a different computer than the install? Or is remote access only capable of being enabled on the server version of webanno?

thanks

**Comment by reckart** [comment]
You should be able to access the standalone version running on another computer by accessing the IP address of the other computer at port 8080 using http (e.g. `http://192.168.0.121/webanno` if the IP of the other computer is 192.168.0.121). It is possible though to configure it so that it cannot be accessed from another computer - if that is desired.

**Comment by Kcanady1** [comment]
So I attempted to do this on multiple computers on different networks, but  each time it only showed a connection timeout page

**Comment by reckart** [comment]
After having started WebAnno try one of the following commands to see what servers you are running:

*OS X*
```
$ lsof -nP | grep LISTEN
java      31117 username   25u     IPv6 0xababababababa        0t0                 TCP *:8080 (LISTEN)
```

*Linux*
```
$ netstat -tnlp
tcp6       0      0 :::8080                :::*                    LISTEN      1068/java
```

If you do not see such a line with java and port 8080, then check the console output of WebAnno for errors. Depending on your system configuration, you might see `tcp` instead of `tcp6`.

**Comment by Kcanady1** [comment]
I've been running webanno natively on a windows machine, so perhaps that is the isssue, I'll try running it on a Linux VM and see if that works

**Comment by reckart** [comment]
It should also work on windows. If you google for “ windows list listening ports” you should find a similar command.

**Comment by Kcanady1** [comment]
I've tried the aforementioned commands, and after I Launch webanno there is something on port 8080 but it's missing the "1068/java",
![tcp outputs](https://user-images.githubusercontent.com/63427745/83648980-b211d280-a584-11ea-8a12-f9cbb49ca72a.jpg)

Additionally when I try to run webanno through the terminal using the " java -jar webanno-3.6.5.standalone.jar" command, all I receive is "Error: Unable to access jarfile webanno-3.6.5.standalone.jar" (Both on Linux and in Windows). How do I go about checking the console output?

**Comment by reckart** [comment]
Does the 8080 line also appear in the output *before* you launch WebAnno? If yes, then you might have something else already running on that port in which case you'd either have to stop that other thing or tell WebAnno to run on a different port.

Regarding starting WebAnno on the command line: does the file `webanno-3.6.5.standalone.jar` exist in the directory where you run this command? The file name also looks odd to me - when you download it, the name should normally be `webanno-standalone-3.6.5.jar`.

**Comment by Kcanady1** [comment]
I just tested it and while there isn't an 8080 line before I launch webanno but after I launch webanno there are two 8080 lines:
TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING       InHost
and
TCP    [::]:8080              [::]:0                 LISTENING       InHost


Regarding the command line issue I was just copy and pasting the command from the user guide and didn't realize the difference in name, that's now working fine.

**Comment by reckart** [comment]
Looks good:

```
TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING InHost
TCP [::]:8080 [::]:0 LISTENING InHost
```

So that means you should be able to open `http://localhost:8080` on your own computer to access it. Now in order to figure out how to access it from another computer on the same network, you need to figure out the IP address of your computer. I think the Windows command for getting your IP address is `ipconfig`.

If you're running this e.g. at home, then another computer in your home should be able to access it - but typically *not* another computer from the internet.

**Comment by Kcanady1** [comment]
Okay, I see, so the standalone version specifically can only be accessed by the host computer and other computers on the network, while the server version can be accessed by anyone with access to the server it's running on. Is that correct?

**Comment by reckart** [comment]
It's not a matter of the software - it is a matter of your computer network setup. The difference between the "standalone" version and the "WAR" version is that the "standalone" comes with an embedded Tomcat server and in order to run the WAR version, you need first install a Tomcat and then drop the WAR into the Tomcat. And because it doesn't bring its own Tomcat, the WAR file is slightly smaller than the standalone JAR file. All the servers I am operating run the standalone version and people on other computers can sure access it.

When you see this:

```
TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING InHost
TCP [::]:8080 [::]:0 LISTENING InHost
```

It means that the service listening on port 8080 (in our case WebAnno) can be accessed from another computer. That's what the `0.0.0.0` is saying. If only access from the server would be possible, it might say something like `127.0.0.1` instead.

Now, the rest is up to your computer. Can the other computer even "see" your server? E.g. if you `ping` the IP address of your server from the other computer, does it work?  Does your server run a firewall or virus scanner which might block the access from the other computer? There's plenty of stuff which could go wrong, but if you see this

```
TCP 0.0.0.0:8080 0.0.0.0:0 LISTENING InHost
TCP [::]:8080 [::]:0 LISTENING InHost
```

and if you **can** access WebAnno on that machine using `http://127.0.0.1:8080` but you cannot access it from **another** computer using `http://<the server address you got via ifconfig>:8080`, then it shouldn't be an issue with WebAnno.
