### ISSUE TITLE
Examples for Dependency/Relation and Link constraints

### ISSUE THREAD

**Issue by nikolausn** [webanno/webanno#1746]
Hi,

I am looking for a way to add rules/constraints for dependency/relation and link but can't find any on the documentation and even on google. Can anyone provide me an example of how we can add rules/constraints on the link or relation?
The basic use case is I want to create an event link, but I want to limit the source and target link to a specific layer.
For example:
- link = move , source = person , target = location
- link = buy , source = company/person , target  = company

I can't find any straight forward implementation for this Webanno tools. 
The reason we need this is to limit errors in the annotation process since annotators often confused if they have so many options. Appreciate your help.

**Comment by nikolausn** [comment]
I am giving up using this tool, I feel so frustrated figuring out how to add proper constraints. 
I look at a similar tool and find brat is my savior. They provided a clear example of the configuration and constraints, and the example they have for BioNLP annotation is exactly what I need ([here is the link](http://weaver.nlplab.org/~brat/demo/latest/#/not-editable/BioNLP-ST_2011_ID_devel/)). If you export the project you can find the configuration example which is really straightforward.
Based on my exploration the good features that this tool provides compared to brat are comprehensive projects and user management as well as task assignment, curation, inter-annotator, and monitoring. 
Hope this "straightforward" dependency/constraint feature will be implemented in the Webanno on the future release.

**Comment by reckart** [comment]
For anybody else who might be interested in how this can be done in WebAnno, here an example.

* Create a new project, upload a simple text document
* Go to the **Tagsets** tab in the project settings
* Create a new tagset `Named Entity Relations tags` and add the two tags `move` and `buy` to it
* Go to the **Layers** tab in the project settings
* Create a new **relation** layer called `NamedEntityRelation`
* Add a **string** feature called `value` to the **NamedEntityRelation** layer
* Configure the **value** feature to use the **Named Entity Relations tags** tagset
* Create a text file called `example.rules` with the following content
```
import de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity as NE;
import webanno.custom.NamedEntityRelation as REL;

REL {
  Governor.value = "PER" & Dependent.value = "LOC" -> value = "move";
  Governor.value = "PER" & Dependent.value = "ORG" -> value = "buy";
  Governor.value = "ORG" & Dependent.value = "ORG" -> value = "buy";
}
```
The **Governor** and **Dependent** names refer to implicit properties of the **NamedEntityRelation**, namely the source and the target of the relation. Since the source/target are of the type **Named entity**, we can write e.g. `Governor.value` to access the value feature of the source named entity annotation.
* Open the **Constraints** tab in the project settings and import **example.rules**
* Open the text document on the annotation page
* Select the **Named entity** layer from the active layer dropdown
* Select some word to create a named entity annotation - set the **value** feature to `PER`
* Select some other word to create a named entity annotation - set the **value** feature to `ORG`
* Select yet another word to create a named entity annotation - set the **value** feature to `LOC`
* Click on the **PER** annotation and drag the relation to the **ORG** annotation
* Note that in the dropdown for the **value** feature, the tag **buy** is at the top and bold
<img width="1096" alt="Screenshot 2020-08-11 at 17 42 23" src="https://user-images.githubusercontent.com/1410238/89918210-09be6100-dbfa-11ea-9a75-eb198c38076a.png">
* Click on the **PER** annotation and drag the relation to the **LOC** annotation
* Note that in the dropdown for the **value** feature, the tag **move** is at the top and bold
<img width="1105" alt="Screenshot 2020-08-11 at 17 41 51" src="https://user-images.githubusercontent.com/1410238/89918255-15aa2300-dbfa-11ea-9842-9efdca88118f.png">

You may note a little green checkmark next to the **value** feature editor field on the right part of the screen. This checkmark indicates that constraint rules are active.

Mind that the constraints only re-order the tags in the dropdown - they do not actually remove choices for the user. So the user is encourage to use one of the tags on which the constraints rules match, but can choose to use another on in case e.g. the rules are incomplete.

**Comment by reckart** [comment]
@An-Feli Would be great if you could transfer that example to the documentation :) The categories for the relation do not really match the text - so either a different example text or different example relation categories would be helpful.

**Comment by reckart** [comment]
@nikolausn Your description seems to imply that "person", "location", "company" etc. are different layers. In WebAnno, you wouldn't model it like that. You would use one layer (e.g. the built-in Named entity layer) and then have a feature on that layer which is controlled by a tagset - then in the tagset you'd have your categories like "person", "location", etc. In fact, the WebAnno by default assigns an example tagset to the **value** feature of the **named entity** layer which defines categories like `PER`, `ORG`, `LOC` (which you are free to change/expand on).

That said - if you want to model events, you'd probably not want to do it using a relation layer, but rather using a so-called "slot feature". So you'd define a span layer which is used to annotate the event trigger word(s). Then you'd define a second span layer for the event participants. Finally, you'd define a slot feature on the event trigger layer which links to the event participant layer. If you have a look at the built-in **SemPred** and **SemArg** layers - that is essentially what they are. The **SemPred** could be used to annotate event triggers (usually a verb) and the **SemArg** layer to annotate the event participants. So in a sentence like `Oracle acquired Sun Micro Systems`, you'd annotate `acquired` as a **SemPred**, and `Oracle` and `Sun Micro Systems` as **SemArg**. You'd set the **category** on the **SemPred** to `buy`. When you link the `Oracle` SemArg annotation to the SemPred, you'd e.g. choose as a role `buyer` and for the other SemArg annotation on Sun, you'd choose the role `bought`.

<img width="1119" alt="Screenshot 2020-08-11 at 18 02 35" src="https://user-images.githubusercontent.com/1410238/89920573-daf5ba00-dbfc-11ea-9b8d-5d2738967256.png">

I won't go into how to define constraints for slot features here because that is [already in the user manual](https://webanno.github.io/webanno/releases/3.6.5/docs/user-guide.html#_constraints_for_slot_features).

**Comment by reckart** [comment]
Excuse any typos ;) Screenshots were taken from [INCEpTION](https://inception-project.github.io) - but it's pretty much the same in WebAnno.

**Comment by nikolausn** [comment]
Hi @reckart, thank you for replying. Yes, I was thinking of using slot feature as well since it's closely related to trigger events. However, my main problem when I tried to implement a slot in my use case was I can't find a way to make a constraint on the slot arguments based on the domain+range dependency. The purpose of limiting the options on the slot arguments is mainly to reduce the annotation mistakes/error and make it easier for the annotator with the guided options. Will the example on the relation that you provided also work on the slot?

**Comment by reckart** [comment]
I tried writing similar rules for slot features, but it doesn't work so far - I get an exception.

Theoretically, one would probably like to be able to write a rule like this: 

```
import de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity as NE;
import webanno.custom.EventTrigger as TRIGGER;

TRIGGER {
  participants.target.value = "PER" & participants.target.value = "LOC" -> value = "move";
  participants.target.value = "PER" & participants.target.value = "ORG" -> value = "buy";
  participants.target.value = "PER" & participants.target.value = "PER" -> value = "buy";
}
```

However, there are two problems: 
* the first problem is that the `participants` feature (a slot feature) allows multiple values - and the current implementation of the constraints don't like that really and throws an exception when we try to access `participants.target.value`.
* the second problem is that we'd really probably like to be able to write something like **if the participant with role `buyer` is a `PER` and the participant with role `bought` is an `ORG`, then the trigger type should be `buy`** - maybe like this:
```
  participants.target[role="buyer"].value = "PER" & participants.target[role="bought"].value = "ORG" -> value = "buy";
```
... but the constraint rule language currently doesn't support this `[role=xxx]` predicate construct.
