### ISSUE TITLE
Design: Import button seems too far in Settings->Documents/Guideline 

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#185]
Although this is mostly based on user's perception but for me the "import" button seems far from the first two _control_ objects required while importing in Documents and Guidelines tab in settings.

If you look at location of import button in other tabs, they are close and it feels right. I think we should have a uniform way and move import button.

![import](https://cloud.githubusercontent.com/assets/1897100/13725816/28ca5ada-e8ad-11e5-9e64-b8a5a5864126.png)

**Comment by reckart** [comment]
The way we handle it is that primary content is left-aligned and buttons are right aligned within a framed area. The areas scale with the width of the browser.

In other tabs, I think this does not appear as much because they are more crowded.

One way to solve this could be to scale the drop-downs with the browser width - but I believe there was some problem that browsers do not really scale drop-downs.
