### ISSUE TITLE
Created users cannot login from their computer

### ISSUE THREAD

**Issue by mclavissiere** [webanno/webanno#1911]
I have created a user in User Management in the home menu and added this user to an annotation projet. When this person tries to log onto Webanno with the username and password I created from her own computer, she receives the error code "Login Failed." I am able to log in with her username and password from my computer successsfully.

Finally, when my colleague tried to create the same user profile on her computer, she received an error message that informed her that the username was already in use.

**To Reproduce**
1. Go to 'Users'
2. Click on 'Create'
3. Enter username and password.
4. Reenter password
5. Select all three roles "ROLE_ADMIN," "ROLE_USER", "ROLE_PROJECT_CREATOR" 
6.  Enable account.
7. Click on 'Save'
8. Go to 'Projects'
9. Select project
10. Go to "User" tab
11. Add user
12. Select all three options of "Manager," "Curator," "Annotator" 
13. Click on 'Save'
14. Colleague tries to login in using created username and password
15.  "Login Failed"  appears, and it is impossible for colleague to access the project. 

**Expected behavior**
Colleague can access project to participate in annotator after user profile is created in the main menu and selected for a project.

**Please complete the following information:**
 - Version and build ID: 3.6.7 (2021-02-27 22:35:18, build afd15dd9ef6da4b4e37713caf06ebd2699cad2ef) 
 - OS: Windows 10 Pro, 64 bit operating system
 - Browser: Chrome and Firefox

**Additional context**

My goal is to use Webanno in a classroom setting, so I will need to have many annotators accessing the project. I currently have not been able to create a user that can access the project from their own computer.

**Comment by reckart** [comment]
The the person logs on from her own computer, what address/URL does she enter into the browser window to access your webanno? Is it `http://localhost:8080` or something else?

**Comment by mclavissiere** [comment]
http://localhost:8080

**Comment by reckart** [comment]
`localhost` always refers to the computer on which the browser is running. So if you start WebAnno on your computer and access it via `localhost`, and your colleague starts WebAnno on her computer and accesses it via `localhost`, then you have two WebAnnos running (one on each computer) and you both access the one running on your respective computers. Hence, when you create an account on your computer, it does not appear on the computer of your colleague because the colleague's computer is running its own WebAnno.

In order for your colleague to access the WebAnno on your computer, you have to figure out the IP address or hostname of your computer. This can be done e.g. by opening a command line / terminal window and using one of the following commands:

```
Windows: ipconfig
Linux / OS X: ifconfig
```

Example:
```
% ifconfig
...
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ...
	inet6 ...
	inet 192.168.0.5 netmask 0xffffff00 broadcast 192.168.0.255
	media: autoselect
	status: active
...
```

Depending on if you use wired or wireless network, there might be different network adapters shown in the output. Typically, you'd look for one called `eth0`, `en0`, `wlan0` or such. Next to the name, there should be a number in the format `XXX.XXX.XXX.XXX` which is the address of your computer on the network. In the example above, the number is `192.168.0.5`.

If you colleague enters that number instead of localhost, then hopefully she should be able to access the WebAnno on your computer. Again considering the example above, your colleague would enter `http://192.168.0.5:8080`.

You could also try using the command `hostname` on the command line and using the name printed by that command instead of the number. E.g. 

```
% hostname
pc-102.local
```

you would try `http://pc-102.local:8080`.

**Comment by reckart** [comment]
I would also like to point you to INCEpTION as a replacement for WebAnno. In particular in the upcoming release of INCEpTION, there is a much better experience for users running the annotation tool on their desktops with a convenient system tray menu that allows stopping the application properly, viewing logs, gives more helpful error messages if there is a problem during start etc. Otherwise, INCEpTION supports almost all of the WebAnno features, is faster, has a cleaner UI and a better overall user experience. Give 0.20.0-rc-8 a try: https://inception-project.github.io/downloads-beta/

**Comment by mclavissiere** [comment]
Many thanks. I will try to test the solution you recommend with my colleague and will check out INCepTION. My students are law students, not linguists (I am a linguist) or computer scientists, so the easier the interface, the better the teaching/learning experience will be.

**Comment by mclavissiere** [comment]
My colleague tried both the address with http://myIPaddress:8080 and http://myhostname:8080, but unfortunately was unable to connect to the project. 

She said that she received the error codes "this website cannot be accessed" and "this page cannot be found".

One question, do I need to be actively signed in to Webanno for my colleague to be able to access the project?

**Comment by reckart** [comment]
You do not need to be logged in, but you need to be both on the same network. E.g. if you are both in the same house, it should work. If you are both connected to the same network in a classroom, it should also work. If you are both at your respective homes and try it, then it won't work. In the latter case, you'd need to be running WebAnno/INCEpTION on a publicly server somewhere (e.g. at your institution).

**Comment by mclavissiere** [comment]
Ok. I will test Webanno with my colleague on the same network with the procedure you gave me at the end of August. I'll look into INCEpTION .

**Comment by mclavissiere** [comment]
An update: I was able to use Webanno with 30 students. Thanks for your help. I have another question, but it is different so I will start a new thread.
