### ISSUE TITLE
"Reverse" deletes relation link

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#256]
If I click on "Reverse" in the Actions box for reversing the slot link, it will be deleted.
CORRECTED: they are normal relations.

Observered in Curation WebAnno -- 3.0.0-beta-2, kp3_dck_role_v01/smpl_dck_bekommen.xmi

**Comment by reckart** [comment]
Slot links can only be defined on span annotations. The "reverse" button should only exist for relation annotations. Can you specific in more detail how to reproduce this effect?

**Comment by mmeva** [comment]
I am sorry, the links are just normal relation links.

**Comment by seyyaw** [comment]
@mmeva If this is in testing, all documents are closed for curation

**Comment by mmeva** [comment]
Yes, I am using the Testing user interface.
What does it mean that the documents are closed?

In the meantime, I also observed this behaviour during annotation (not curation).

**Comment by aakashysharma** [comment]
I was unable to reproduce this in a fresh project. I'm currently investigating the project mentioned for reporting this.

**Comment by aakashysharma** [comment]
@reckart I investigated further on this. I think I have found the source of the issue.

In `AnnotationDetailEditorPanel.java` for method `private void actionReverse()`

In line 849, we delete the arc from CAS
In line 863, we loop over and re-add arc reversing it.
And later we persist it.

However, in this particular case, `featureModels` is an empty list!
That's why we only see arc getting deleted, without a new one getting added.

Also, I'm unaware of how to create such arcs of type SemPredPart to test whether it's related to this particular document or to all such types.
![screenshot at 2016-05-11 21 38 50](https://cloud.githubusercontent.com/assets/1897100/15194090/55228ccc-17c1-11e6-8549-f8b6f40fb31b.png)

**Comment by reckart** [comment]
Sounds like you are on a good way, great :)

Try creating a new span layer in the project settings - give it any name.
Then create a new relation layer and select the previously created span layer under "attach to" - do not add any features to this layer.

Mind that for each span layer, you can only create at most one attaching relation layer (a nasty limitation that we currently have...).

**Comment by aakashysharma** [comment]
@reckart So, I created a layer with type 'Span'. And then relation layer attached to the span layer.

I created arc similar to the one described in this issue. Reversing deletes as again `featureModels` is an empty list.

**Comment by reckart** [comment]
I guess the creation of the arc and the adding of feature values needs to be decoupled. First create the arc after reversing, then add feature values (if any).

**Comment by reckart** [comment]
I think I hit a similar problem some time back when annotations that had no features were not even created in the first place.
