### ISSUE TITLE
Last value for feature is used as default for next annotation

### ISSUE THREAD

**Issue by dodinh** [webanno/webanno#26]
How to reproduce:
- Create an annotation A of any kind, set value of feature f to "something" 
- Create an annotation B of the same kind

The value of feature f is pre-filled with "something". This can be confusing for users, e.g. for features which are "not mandatory" to fill in, and can potentially produce a lot of annotation errors.

I can see the value for projects for which features will have the same value a lot of times. So instead of removing the pre-filling, would it be possible to make it optional (probably as a setting on feature level)?

**Comment by reckart** [comment]
That's not a bug, it's a feature. It was introduced to allow a more rapid annotation. 

Looks like it was a bit premature to make this behavior default.

**Comment by reckart** [comment]
I wonder on which level this should be set:

* should it be a per-feature setting
* should it be a per-layer setting

I also wonder where it should be set:

* by the project manager in the project settings
* by the annotator in the annotation preferences

I'd personally tend towards a per-feature setting that is controlled by project manager.

**Comment by lylejm** [comment]
I would love to see this as a per-feature setting controlled by the project manager.

**Comment by reckart** [comment]
Another question came to mind: whether this should be enabled or disabled by default.

I'd vote for this behavior to be disabled on default.

In order to keep implementation effort reasonable, I'd also vote for having this feature **disabled** on any existing features after upgrading to a version of WebAnno that supports this feature from a version that didn't. That means, to restore the previous behavior, the project managers would have to explicitly go to all the features and re-enabled the setting if they want it in all their existing projects.

**Comment by lylejm** [comment]
I'd agree with having this disabled by default.

**Comment by reckart** [comment]
Implemented as described above.
