### ISSUE TITLE
Non token character TSV import breaks sentences display in brat

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#313]
If the CAS contain non-token elements, such as new lines or spaces, WebAnno TSV imports break, reported by @ChrisBieTUDA . Example

```
1-35	269-275	konnte	VMFIN	
1-36	276-277	.	$.	

#Text=Die inzwischen zur ....
2-1	279-282	Die	ART	
2-2	283-293	inzwischen	ADV	
2-3	294-297	zur	APPRART
```	

As it can be seen above, there is non-token element between token **1-36** and token **2-1**

The display looks like the following:
![image](https://cloud.githubusercontent.com/assets/1056051/16818813/f0bea238-4949-11e6-9a54-6d0f857c6361.png)

Temporary solution: 
During import, add **n SPACE** characters, based on offset differences, for brat to properly display the sentences.
Downside: If the original character was different from SPACE char, the text will be different

**Comment by reckart** [comment]
What do you mean by "If the CAS contain non-token elements, such as new lines or spaces, WebAnno TSV imports break?" The CAS is generated from the TSV? How can it contain anything that is not in the TSV? And the TSV cannot contain non-token elements...

**Comment by seyyaw** [comment]
For example, we have the "SPACE char" in the CAS between the sentences but not part of the sentence.
I o not know how that happen, may be the Textreader do it so. You can check the specified file in the figure above in our exp intalation.

**Comment by reckart** [comment]
But you say the problem happens on TSV import... so you are using the TsvReader, not the TextReader. Can you what actions to perform to reproduce the situation that you describe?

**Comment by reckart** [comment]
I don't see any problem looking at your example snippet. I don't even know what to look for.

**Comment by seyyaw** [comment]
The export works correctly (for sentences in the CAS), showing the begin/end of tokens. In the above example, what is is missed is between offset 277 and 279.

**Comment by reckart** [comment]
I thought you were ignoring the offsets during import. But you don't? So you try reconstructing the CAS so that it matches the original offsets?

**Comment by seyyaw** [comment]
Yes, that is what I am proposing as a solution now
If you send the offsets and the sentences as it is (without padding space), brat breaks...

**Comment by reckart** [comment]
Yes, if you would be using the offsets as they are, it would break - not only brat, but the whole CAS would be messed up. Either you would need to completely ignore the offsets. But I prefer your idea of reconstructing the CAS text in such a way that the offsets are correct. 👍

**Comment by seyyaw** [comment]
ok, closing...

**Comment by reckart** [comment]
Actually, it would be best if we would *retain* the text between sentences in the TSV, e.g. as

```
1-35	269-275	konnte	VMFIN	
1-36	276-277	.	$.	

#Text= \n

#Text=Die inzwischen zur ....
2-1	279-282	Die	ART	
2-2	283-293	inzwischen	ADV	
2-3	294-297	zur	APPRART
```	

So the new line I inserted here `#Text= \n` represents the text *between* the two sentences. It also encodes the newline character. In that way, performing an export of some CAS to TSV and importing it again would better preserve the text and formatting. To completely preserve the formatting, we would also have to add a new special column that contains the *text between tokens*.

@ChrisBieTUDA @seyyaw opinions?

**Comment by reckart** [comment]
I should point out that recently we had a user asking about preserving multiple consecutive line breaks (i.e. paragraph boundaries). The modification I suggested would also cover that request.

**Comment by seyyaw** [comment]
Yes, but exporting currently depend on sentences. The problem is, this stuff are not considered as sentences when the TextReader imports.

**Comment by reckart** [comment]
I don't suggest that we support annotations between sentences or texts without sentences. I am just suggesting that we preserve text (including tabs, newlines, etc.) between sentences (and between tokens).

**Comment by hterhors** [comment]
Hi, 

we have recently (yesterday) tried your export and import function of annotated documents (using tsv3 format) with the current WebAnno-Version in the master-branch. But it seems like there are still some issues.

The problems appears while importing documents in TSV-3 Format that contain sentences with new-line chars (not formatted as '\n' but real newlines )

The text of a sentence is split into multiple lines but only one line in marked as "#Text" 
While importing the following exception occurs:

`IO Error while uploading document Wisemanetal.tsv: IOException: 30DE54F2A8AFE5509837CB3F902413F1_14695384775912531449880006740223tabs_panel_content This is not a valid TSV File. check this line: <First Line after new line>
`

Attached the file (in txt since tsv is not supported by github
[Wisemanetal.txt](https://github.com/webanno/webanno/files/385578/Wisemanetal.txt)
) that throws exception.

Best regards,
Hendrik

**Comment by seyyaw** [comment]
Hi @hterhors Thank you for reporting this. I will investigate

**Comment by seyyaw** [comment]
@hterhors Did you export this file from WebAnno ? It seem the file do not conform the WebAnno TSV export format. Currently, during export, such new line in a sentences are removed and the whole sentence remain in a single line. That is why the import fails for you. 
May be I extend the export format, where a new line in a sentence start with a special tag such as **#TextSubSent** 

And this issue tackles different issue (wrong offset due to new line while using TextReader (not TSVReader) ). I create new issue for this one

**Comment by hterhors** [comment]
> @hterhors Did you export this file from WebAnno ?

Yes.

>  It seem the file do not conform the WebAnno TSV export format. Currently, during export, such new line in a sentences are removed and the whole sentence remain in a single line. That is why the import fails for you.

I took the latest version from the master-branch(1 Week ago probably). I thought you'd change some things @see previous comments. 
 
> May be I extend the export format, where a new line in a sentence start with a special tag such as #TextSubSent

That might work.

**Comment by seyyaw** [comment]
The related issue  #318 is solved. This should be closed

**Comment by reckart** [comment]
Please check again https://github.com/webanno/webanno/issues/313#issuecomment-232487550 - we have this issue here and we have had requests on the mailing list about being able to have empty lines between sentences (which are currently not preserved by TSV).

The format would greatly profit from the ability to also record text between sentences because in that way we can capture the *complete* original text and not only parts of it, e.g. 

```
...
1-35    269-275 konnte  VMFIN   
1-36    276-277 .   $.  

#Text= \n

#Text=Die inzwischen zur ....
2-1 279-282 Die ART 
2-2 283-293 inzwischen  ADV 
2-3 294-297 zur APPRART
...
```

**Comment by seyyaw** [comment]
@reckart  My only problem here is that we so far depend on Sentence annotations. If there is no Sentence annotation with a content of only **new line**, how could we get that while exporting. So, if we have a CAS with new lines not recorded as sentences (example when using the  DKPro Textreader) it is difficult to export those new lines.
But the question is to import TSV files marked with a new line marked as **#Text= \n**, that will not be a problem.

**Comment by reckart** [comment]
@seyyaw I also see a problem regarding the sentences... what I don't know is how much trouble it causes - maybe you have an idea.

But first one part I didn't understand: If we import a document that does not contain **any** sentence (or token) boundaries, then WebAnno creates them. So e.g. when importing via the DKPro Core TextReader, WebAnno creates sentence and token annotations. I didn't understand what you meant here.

Now what I don't know (and didn't check atm) is what happens when we import a document that contains **some** sentence annotations:
* I believe what happens is that parts of the text that are not covered by a sentence annotation (and by token annotations) would not show up in the UI
* but I also believe(/hope) that WebAnno would not crash

If we would export such a document e.g. as text or as XMI, the parts of the text that were not covered by sentences would be there again - they are in the text, just not annotated.

But with TSV, now we only get the parts that are covered by sentences. To fix that, we'd have to detect which parts of the text are **between** sentences and to to create such a standalone `#Text=...` for them. 

When reading a standalone `#Text=...` line (i.e. one without any tokens under it), then we should not create a sentences annotation for it - we would assume that it was text between two sentences (because per convention sentences contain tokens).

Does that make sense to you? What kinds of problems do you see?

**Comment by seyyaw** [comment]
The problem is, DKPro Core TextReader
1. set text : Copy the entire text to the CAS --> that means, everything including newlines are copied to the CAS text
2. set annotation: The sentence and token annotation exclude the newlines.
And I use the sentence annotations for TSV export hence missed the newlines.  The only option I can see is: 
1. Iterate the sentence annotation and get the sentences (texts) 
2. Go to the original texts and compare the sentence one by one. when newlines found after a sentence, obtain and export them. I will see how long this will take me

**Comment by reckart** [comment]
@seyyaw

The problem is not the newlines or the DKPro Core TextReader. The problem is *any* kind of text that exists outside sentences. This could also happen in TCF or XMI imports.

How about trying this:

* iterate through the sentencess
* if the current sentence.start != lastSentence.end -> create a `#Text=<text between lastSentence.end and sentence.start>`
  * for the first sentence, consider lastSentence.end to be 0
* after reading the last sentence, check if sentence.last < documentText.length. If yes -> e a `#Text=<text between sentence.end and documentText.length>`

**Comment by reckart** [comment]
Btw. the sentence end offset and the offset of the last token in the sentences should be the same. Newline characters should never be part of sentences.

**Comment by reckart** [comment]
Just noticed that CoNLL-U are having a similar discussion about preserving proper sentence text and inter-sentence text: https://github.com/UniversalDependencies/docs/issues/332
