### ISSUE TITLE
Export / Import Annotations to / from Brat Format

### ISSUE THREAD

**Issue by hterhors** [webanno/webanno#328]
Is there currently a way to export annotations in to the standard Brat-file format as described here [http://brat.nlplab.org/standoff.html](brat)?

This would be a nice feature. Same for import documents from Brat-format. 

Greetings,
Hendrik

**Comment by reckart** [comment]
The import/export for brat is not entirely trivial. But you can try doing a conversion outside of WebAnno. When you do that, you will notice why it is not trivial. But that said, it may still work for you.

* Export the files as XMI
* Build a DKPro Core pipeline that reads the XMIs and uses the [BratWriter](https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/format-reference.html#format-Brat) to export to brat format

If you want, I can send you an example of a brat->XMI pipeline I had set up for one user who wanted to *import* brat into WebAnno. 

Presently, I don't have a ready XMI->brat example - but it should be easy to do because the BratWriter in DKPro Core is quite good at auto-detecting the type system and exporting it.

**Comment by hterhors** [comment]
Thanks for fast response,

I think I'll try to do it on my own first. If it does not work I will ask you for an example pipeline.

Thanks

**Comment by apiad** [comment]
Is there any update on this. I currently have some files annotated in Brat I would like to import to WebAnno to do an inter-agreement check, and then continue tagging on WebAnno. I could manually re-tag inside WebAnno since it's not that much annotated yet, but it would be very nice to be able to automatically import the .ann files.

**Comment by reckart** [comment]
The schema specification in brat is very different from the one in WebAnno. It can often be mapped, but this is a task that needs to be done manually. As it happens, I was just looking into such a case anyway.

Here is a gist for the moment. I hope to refine this and eventually add it to some proper documentation.

https://gist.github.com/reckart/306b8ffddd30bee1f3afd0468a9ad31d

**Comment by jloveric** [comment]
Standoff is a nice format! 👍

**Comment by reckart** [comment]
* https://github.com/inception-project/inception/issues/4498
* https://github.com/inception-project/inception/issues/2424
