### ISSUE TITLE
RemoteAPI source file state

### ISSUE THREAD

**Issue by erikpetersonpb** [webanno/webanno#339]
I've have been experimenting with the Remote API.  I have noticed cases where I get the list of source documents and the state of the document does not seem to update and match what I would expect.  For example, a document starts with the state of "NEW".  I then start annotating it.  When I pull up the list of annotation documents for the document it shows it "INPROGRESS" with me as the user.  However, the state of the source document is still "NEW" where I would expect "ANNOTATION_INPROGRESS".  The source document state isn't being updated even after I finish annotating the document.

**Comment by reckart** [comment]
That is entirely possible. I had a brief look recently at the state tracking of source documents due to another issue and also noted that it was not quite working as it should be. At the moment, it seems to be mainly used to track the curation state of a document, but not really anything that happens before curation...
