### ISSUE TITLE
Custom layer not available for individual users

### ISSUE THREAD

**Issue by hartumat** [webanno/webanno#342]
After creation of a custom layer (span, attached to nothing; allow stacking, crossing sentence boundaries and multiple tokens), this layer is not available for annotation by an admin* user (with full permissions: admin, creator, user) -- only for user roles. We are using WebAnno 3.0.0.

Cheers,

Matthias

*) Certainly not the best way of user management -- point taken. ;-)

**Comment by reckart** [comment]
Since WebAnno 3.0.0 has not been released yet: what exact version are you using? Can you please paste here the full version string including the build hash shown at the bottom of the screen when you open WebAnno?

What does it mean "not available"? Did you open the "Settings" dialog on the annotation page (not in the project settings) and check if the layer is maybe "hidden" for that particular user?

**Comment by hartumat** [comment]
D'oh. Could be fixed by setting the checkbox in the "Settings".

Thanks for looking into this,

Matthias
