### ISSUE TITLE
Sentence up/down buttons not working properly

### ISSUE THREAD

**Issue by maxxkia** [webanno/webanno#392]
I have WebAnno 3.0.0-beta-7 running on Chrome browser. When I am working with sentence up/down buttons (in page section on top of page) I experience problems. Whenever I keep clicking on either up or down button, after several clicks (almost always after 3 clicks) the button just doesn't work any more. So I have to move the cursor to somewhere else on the page and then again hover the up/down button and keep clicking on the button (again same results).

- [x] Annotation page
- [x] Automation page
- [x] Correction page
- [x] Curation page

**Comment by reckart** [comment]
Since commit 1fd0a971db88e560a138c0366f079291c1988d0b, the number field no longer issues AJAX requests. You can change the number or enter one manually without any delays. The actual "jump" is only executed when you click on the "Go to" link below the field. This has been fixed on the annotation, correction, and automation pages. The curation page is still on the todo list.

**Comment by reckart** [comment]
Curation also fixed in 006214a48c6d5416749478c7a4d95ab7a6e4d340.
