### ISSUE TITLE
Sentence-level annotation

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#393]
Would be great to be able to the sentence numbers that appear on the left side of the annotation UI, like 1, 2, 3, 4, 5, etc.

This would be useful for tasks like intention classification, in which labels should be assigned per sentence / utterance.

Examples for home automation virtual assistant device
1| turn on the light   --> text region in "1" should be annotatable as "intent_light"
2| turn on TV ---> "2" is annotated as "intent_tv"
3| turn on my lights a bit  ----> "3" is annotated as "intent_light"

That's just an example, though.
It does not have to be the sentence index number text. there could be a selection box/boxes column between the sentence index region and annotation UI region.

**Comment by reckart** [comment]
@GiantEnemyCrab your first sentence seems to be lacking a word? "... to be able to **?** the ..."?

**Comment by GiantEnemyCrab** [comment]
Edit:

*would be great to be able to "annotate on" the sentence numbers

**Comment by reckart** [comment]
Would you imagine that to be a shortcut that creates an annotation over the whole sentence span and renders as usual as a label spanning over the whole sentence?

**Comment by GiantEnemyCrab** [comment]
it's a bit different from a shortcut.

It is correct, that it is a bit clunky to highlight the sentence from the start to period (and if I miss the period position by some pixels while mouseUp, it ends up not annotating what I thought I highlighted, so I would need to redo the process of highlighting the entire sentence)

But it is more for visual cleanness. If this task is multi-layered, where "intention" layer exists to annotate the overall classification label, there is another layer for "concept".

A sentence could have:

1|turn on the light blue ---> in this case, intention layer is "intent_light", but "blue" would be assigned a concept annotation of "color" in the concept layer.

It would be cleaner to see separation of intent and concept layers for all sentences that exist in the annotation document.

Technically, it is possible to do the annotation task with current features, annotating some substring of a sentence after the entire sentence is annotated, etc.

It is also technically possible to do some work-around to avoid overlapping of annotation in some text spans, by preparing the document, such that each sentence starts with a dummy string like line number (#1, #2, #3, etc), so that these dummy line numbers will be reserved for annotating intent classification labels for visual cleanness. But this is a work around, where post-processing is necessary to account for these dummy string addition in the end. It's a workable solution, but not as clean of a solution. Sentence-level annotation feature from WebAnno would be a cleaner solution.

**Comment by kazukisan** [comment]
I am coming back to this feature request, and this could be actually implemented as a short cut, as you mentioned much earlier.

#443 will consolidate "lock to": 1. characters, 2. a single token, 3 multiple tokens in the layer config UI.

There can be an additional option to "lock to a single sentence", in a layer configuration. BRAT UI js would need to change accordingly, but I can see an implementation like this being pretty clean from the coding point of view.

UI does gets a little quite colorful and cluttered when all the text is highlighted, but perhaps stealing some horizontal space by implementing the way I originally suggested may have different kind of cluttering effect in the end.

This new comment, "lock to a single sentence", I feel, would be a clean way to implement this.

**Comment by reckart** [comment]
Sounds reasonable.
