### ISSUE TITLE
User cannot import project (WebAnno 3)

### ISSUE THREAD

**Issue by neumannm** [webanno/webanno#395]
Don't know if this is a bug or a feature, but I just noticed that I'm not able to import a project as a user (WebAnno 3.0.0-beta7). The "Import project" box is there but nothing in it. The buttons are there in the admin account. My user account has the role of "project creator".

If this is meant to be like this, that users other than admin are not allowed to import an existing project, then the box should be hidden, otherwise it's a bit confusing. Although I think it should be possible for a normal user (at least those with role "project creator") to import a project.

**Comment by reckart** [comment]
Project creators can create projects, but they cannot import projects. The reason is that importing projects usually requires creating the user-accounts of the users in the project (if they are not already available on the system) and user-creation is something that only admins can do.

So it's a feature.

The bug is that the import-project box is still rendered but empty. It should not be there at all.

**Comment by neumannm** [comment]
Ok I see your point. So yes, this box should not be rendered at all. :)
