### ISSUE TITLE
Interface jumps to the top in Curation mode

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#418]
This is very similar to an issue reported in #331, and happens in Curation.

In curation view, if I try to add an annotation to curated document from annotator's document which may appear toward the bottom, when I click to accept this annotator's labeling, the page jumps back to the top.

It gets tedious for curators, having to scroll to the bottom again and again, if the curator plans to accept a lot of annotations from this user, whose content may be displayed to the bottom.

"Bottom" in this context would mean the very bottom of the page, and the page is vertically long enough to be able to scroll down.

**Comment by reckart** [comment]
Yep, the AJAX updates on that page should be handled differently - probably also affects the correction and automation interfaces. Due to the architecture of those pages, it I believe it is quite a bit more effort to fix this than on the annotation page.

**Comment by reckart** [comment]
@kazukisan I think that PR https://github.com/webanno/webanno/pull/793 fixes this issue in curation, correction and automation views. Instead of re-rendering the user annotations via Wicket AJAX, updated data is sent selectively to brat views. I did some basic local testing and things still *seem* to work. If you can spare some time, it would be great if you could give it a try as well before merging this into the main branches.

**Comment by kazukisan** [comment]
Thank you for this commit, and yes it is working well on my end!
