### ISSUE TITLE
Webanno 3.0 TSV3 Export Time

### ISSUE THREAD

**Issue by Tiberiu17** [webanno/webanno#423]
Hi,

I would like to raise the issue of the time it takes to export the whole project in the new TSV3 format. For example, for a 50MB annotation project, with around 45 files, it takes 3-4 hours to do a full export. 
Can it be done something to shorten the time? With the previous TSV for Webanno 2.3.1 it took far less time to export, probably it would have taken 10 minutes for the same project.
Would it be also possible to have the option to export in the older TSV2 format?

Thank you.

**Comment by reckart** [comment]
Uhm... actually the code is in WebAnno 3 still. However, I don't know if it would still work if you register the writer. You can try creating your own `formats.properties` file in your webanno home folder based on [this one](https://github.com/webanno/webanno/blob/master/webanno-webapp/src/main/resources/META-INF/formats.properties) and add 

```
ctsv.writer=de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv2Writer
```

**Comment by Tiberiu17** [comment]
Thanks for the reply. I tried and it didn't work, in both standalone and server version.
If you could in the future implement a way to export projects from Webanno 3.0 in the older 2.0 format it would be very helpful.

**Comment by Quadrocompile** [comment]
Or you could just "fix" the WebannoTsv3Writer class. To all people working on the source code of WebAnno: you might want to read this [interesting article](http://chrononsystems.com/blog/hidden-evils-of-javas-stringsplit-and-stringr)

Regarding the WebannoTsv3Writer class there are some serious issues with your implementation that could well be responsible for the bad performance. I have not profiled the functions yet so there might be some other problems with the code, anyways you should definetly attend to the following subject.

The function replaceEscapeChars(String) in line 827 is called from three points in the actual source code and all usages are within for-loops. Therefore I assume, that this function is called quite often. The problem with this function is, that String.replace(pattern, replacement) creates a Pattern object each time it is called, for static tokens which is a significant overhead. And you build 10 Pattern objects for each call of the function, processing the input string with 10 regex NFAs.

I made a quick jhm benchmark comparing your function to an improved version which utilizes a single regex pattern (instead of 10) that is precompiled once instead of every time this function is called. The benchmark showed, that the improved function is nearly 10 times faster. Depending on how often exactly this function is used (especially when exporting 45 documents) this could heavily decrease the overall export time. So I suggest that you profile your export function and consider changing it.

As a sidenote: I encountered a similar problem while working with a huge corpus file. Building regex objects is so expensive compared to other calls that replacing the split and replace calls in a heavily used routine reduced computation time from 10 to just 2 minutes.

[RegexBenchmark.java.txt](https://github.com/webanno/webanno/files/814803/RegexBenchmark.java.txt)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MICROSECONDS)
Benchmark                                Mode  Samples  Score  Score error  Units
c.q.r.RegexBenchmark.testImpovedRegex    avgt       25  0,386        0,023  us/op
c.q.r.RegexBenchmark.testWebAnnoRegex    avgt       25  3,325        0,035  us/op

A draft of the improved function:
private static final Pattern REPLACE_ESCAPE_CHARS_PATTERN = Pattern.compile("(" +
            Pattern.quote("\\") + "|" +
            Pattern.quote("[") + "|" +
            Pattern.quote("]") + "|" +
            Pattern.quote("|") + "|" +
            Pattern.quote("_") + "|" +
            Pattern.quote("->") + "|" +
            Pattern.quote(";") + "|" +
            Pattern.quote("\t") + "|" +
            Pattern.quote("\n") + "|" +
            Pattern.quote("*") +
            ")");
private String replaceEscapeCharsImproved(String annotation){
        Matcher m = REPLACE_ESCAPE_CHARS_PATTERN.matcher(annotation);

        StringBuffer sb = new StringBuffer(annotation.length()*2);
        while (m.find()) {
            String token = m.group(1);
            switch (token){
                case "\t":
                    m.appendReplacement(sb, Matcher.quoteReplacement("\\t"));
                    break;
                case "\n":
                    m.appendReplacement(sb, Matcher.quoteReplacement("\\n"));
                    break;
                default:
                    m.appendReplacement(sb, Matcher.quoteReplacement("\\"+token));
            }
        }
        m.appendTail(sb);
        return sb.toString();
}

Kind regards and happy coding!

**Comment by reckart** [comment]
@Quadrocompile thanks for looking into this. That function is definitely a bottleneck. I replaced it with a call to Apache Commons StringUtils.replaceEach() which is optimized to handle this type of replace cascades. The speedup is comparable to the one from your experiment. But by using StringUtils.replaceEach(), we don't have extra code to maintain, so I chose that implementation.

**Comment by reckart** [comment]
Looks like `WebannoTsv3Writer.setAmbiguity()` is at least something like O(n^2). It goes over all annotations in all layers and calls `isMultipleTokenAnnotation()` which in turn iterates over all *annotation units*.

**Comment by reckart** [comment]
The new TSV3 reader/writer implementation being prepared in #676 solves the speed problem.
