### ISSUE TITLE
Bug Features-dropdown: Selecting tags twice

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#449]
After creating a span-annotation and while selecting a feature, webanno reloads the Features-box. Thus the annotator has to select and assign the wanted tag in the drop-down a second time.
I added a short gif:
![doubleselect-bug](https://cloud.githubusercontent.com/assets/19265315/23354606/52958b66-fcd2-11e6-9c59-ecd37195963c.gif)

This happens on two different systems, using chrome and firefox on 3.01.

**Comment by reckart** [comment]
I think the problem is that after creating the span annotation, the focus gets set of the first element of the detail panel (here "error" text field). By clicking on the dropdown, the focus leaves the text field which triggers a "save" action which in turn reloads the panel. 

There are a couple of options:
* triggering save/reload only if the value of a field has actually changed
* reloading only those fields which need to be updated (e.g. due to constraints) instead of reloading the whole detail panel
* setting the field values / showing / hiding fields surgically through ajax javascript instead of reloading the panel

Trying to detect changes is probably the easiest and should already help quite a bit.

**Comment by reckart** [comment]
As a workaround, click somewhere on the screen after changing a dropdown field and wait until the AJAX request is complete before you make a selection in the next dropdown.

**Comment by reckart** [comment]
The fix to https://github.com/webanno/webanno/issues/480 should also mitigate this issue here. The feature editor panel is now only re-rendered when a values is changed. The case in the video is covered. However, if the user would enter a value into the first text field and after that start selecting a value from the dropdown, the issue will still show up.

**Comment by astier** [comment]
I am not sure if it is the same bug but what I encounter is when I create an annotation and then change the layer by clicking yes in the pop-up window which asks me if I want to delete the existing annotation then all existing features for the newly selected layer are reloaded three times in a row and also rendered 2 or 3 times.

For example I have a layer with two features called Entity and Aspects. Each of them with a tagset. I let print a notification each time the private method loadFeatureEditorModelsCommon in ADEP get called and reaches the place (~line 1020) where the tagsets are loaded. The printed output when performing something like described above is then:

> 2017-07-12 14:30:55 INFO [admin] CasStorageServiceImpl - Updated annotations for user [admin] on document shakespeare in project Entities and Aspects
LOAD TAGSET FOR FEATURE Aspect
LOAD TAGSET FOR FEATURE Entity
LOAD TAGSET FOR FEATURE Aspect
LOAD TAGSET FOR FEATURE Entity
2017-07-12 14:30:55 INFO [admin] CasStorageServiceImpl - Updated annotations for user [admin] on document shakespeare in project Entities and Aspects
LOAD TAGSET FOR FEATURE Aspect
LOAD TAGSET FOR FEATURE Entity
2017-07-12 14:30:55 INFO [admin] ApplicationPageBase - admin: The [Entity] annotation has been deleted.
2017-07-12 14:30:55 INFO [admin] ApplicationPageBase - admin: The [Entity and Aspect] annotation has been created/updated. Label: [(Entity and Aspect)]

**Comment by reckart** [comment]
@astier it might be related, but I would treat it as a separate issue. You issue seems to be about performance while the present issue here is about usability. They might be addressable in different ways.

**Comment by reckart** [comment]
As much as it is possible, this should have been addressed as part of #1694 as the updates to the sidebar are very selective and minimal now.
