### ISSUE TITLE
New WebAnno remote API

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#455]
Implement a new remote API for WebAnno with a more systematic API design and a more maintainable backend implementation.

**Project**
- [x] project list - list projects
- [x] project create - create a new project
- [x] project read - get project information
- [x] project delete - delete a project
- [x] project export - export a project as a ZIP file
- [x] project import - import a project as a ZIP file

**Document**
- [x] document list - list documents in a project
- [x] document create - import a document in a specified format
- [x] document create parameter `state` - allow document to be created in a specified state (Allowed: NEW, ANNOTATION-IN-PROGRESS) 
- [x] document read - export a document in a specified format
- [x] document delete - delete a document from a project

**Annotations**
- [x] annotations list - list which users have annotations
- [x] annotations create - create/overwrite a users annotations by importing from a specified format
- [x] annotations create parameter `state` - allow annotations to be created in a specified state 
- [x] annotations read - export a users annotations in a specified format
- [x] annotations delete - delete the annotation document record from the DB and the latest file. It will seem to WebAnno as if the annotation document was never created. If WebAnno is configured to maintain a backup history, this history will be retained (minus the latest file of course).

**Curation**
- [x] curation create - create/overwrite a curation by importing from a specified format
- [x] curation create parameter `state` - allow curation to be created in a specified state (actually is the document state. Allowed: CURATION-IN-PROGRESS, CURATION_FINISHED) 
- [x] curation read - export a curated document in a specified format
- [X] curation delete - delete the latest curation file. It will seem to WebAnno as if the annotation document was never created. If WebAnno is configured to maintain a backup history, this history will be retained (minus the latest file of course).
- ~~curations list~~ - this is not necessary since a) there is only a single curation per document and b) the curation status of a document is provided in the *document list* call.

**Misc**
- [x] allow messages in response (https://github.com/webanno/webanno/issues/455#issuecomment-283011969)

**Undecided**
- [X] conflate curation with annotation API using a special username <-> having a dedicated curation API parallel to the annotation API -> **decision: separate set of calls for curation**

**Comment by reckart** [comment]
@GiantEnemyCrab care test-driving? ;) I think some of the requests you had for the old API are not yet supported, but we can add them. Nice thing with the new API - try this:

* log in to WebAnno
* go to `<http://your-normal-webanno/url>/swagger-ui.html`

**Comment by GiantEnemyCrab** [comment]
Thanks for the heads up! The v2 API convention for simplifying CRUD looks clean.

I have tried several of the "GET" API endpoints in v2 and they seem to work fine so far.
I will try "DELETE" and "POST" tomorrow here in US Eastern time.
POST annotations documents with userId is nice. Thanks for implementing it.

By the way, I did notice one thing:
```
GET /api/v2/projects/{projectId}/documents/{documentId}annotations/{userId}
POST /api/v2/projects/{projectId}/documents/{documentId}annotations/{userId}
```
There should be a slash between {documentId} and annotations/ there.

I think this is on the way to be implemented in some form anyway, but would be good to have
GET/POST /api/v2/projects/{projectId}/documents/{documentId}/curations

**Comment by reckart** [comment]
Right, those URLs are missing a mistake. Fix committed.

**Comment by reckart** [comment]
@GiantEnemyCrab - I am unsure whether to have a separate set of calls for curation or whether to map curations to a special user ID `CURATION_USER` (as we actually do it in the backend).

**Comment by reckart** [comment]
@GiantEnemyCrab I'm probably going to change the response format soon. There are presently two options I am thinking of:

* only changing the response for errors from plain-text to JSON, e.g.
```
{ error: "Some error occurred" }
```
* changing all responses to allow extra messages, e.g.
```
{
  messages: [
    { level: "warn", text: "Unable to read document XXX, excluded from result" }
  ],
  body: {
    // here goes the current response structure
  }
} 
```

**Comment by GiantEnemyCrab** [comment]
Allowing extra messages looks more clear and flexible in the end

**Comment by kazukisan** [comment]
For curation, with API V2 convention, I can see how having curations calls could be useful and valid:

 curations list - list curation_finished documents
 curations create - Not Applicable
 curations read - export curation_finished document
 curations delete - "Re-create Merge" (basically start curation from scratch)

Also, I have had a request to reset annotation by an annotator at least. This happens when an annotator is given some documents and want to do annotation from scratch, because the document has become too messy

So,
annotations delete - removes existing annotations from a document
is a valid call.

**Comment by kazukisan** [comment]
In addition to "format" optional parameter, it would be great to have "status" as an optional parameter when importing a document.

annotations create - "status" can be either "New", "In Progress" or "Done".
In some workflow, re-import of documents as particular annotators could be a result of an external clean-up script. This clean-up is based on documents that annotators already clicked as "Done". So it is good to keep them as "Done". (Clean-up could be when annotators accidentally included punctuations in annotation, and punctuations are not needed, so an external script just cleans this up, etc)

Default status could be "New" though.

**Comment by kazukisan** [comment]
Another thought.

I mentioned earlier that 
curations create is Not Applicable
, but I think it is applicable.

For uploading curation documents, the current V2 convention would be to use
annotations create - userId (CURATION_USER)

But CURATION_USER is a hard coded value, and something that not everybody would about right away. Sure, this can be documented somewhere, but this is more of an internal value of the Java code.

"curations create" can offer a layer of abstraction into this hard coded value, and  this can be more robust to changes. What if this CURATION_USER value changes in the future (or, want to change it to something else at some point)?

With "curations create", such a change can be handled within the API call, so that consumers of API would not need to change their CURATION_USER value, if the value change ever happens.

In general, uploading a curation document though API sounds strange, but it could happen when the annotation spec changes, and changes could be applied in a programmatic way to already curated documents.

**Comment by reckart** [comment]
Handling curations through the annotation API would also make it problematic to change WebAnno such that multiple users could curate independently at some point. A user could then only be either a curator or an annotator on a project, but not both.

**Comment by reckart** [comment]
Well, not true... a user could still be annotator and curator as it is presently the case too.

I guess the question is rather: could there be a reason to have at some point multiple different adjudications of a single document or will there always only be one single adjudicated version (i.e. are all curators always working on the same adjudicated version of a document). 

I guess at least for the foreseeable future, there can only be a single curation for any given source document.

**Comment by kazukisan** [comment]
There should be only a single curation version.

But annotation spec change can occur, which would trigger necessity of changing the curation.
It could be renaming of a tag. It could be change in inclusion of punctuations or not.

Those changes can be updated programmatically, rather than going over every document manually in curation.
So that's the motivation for curation doc "CREATE" API end point, and not for having (or motivate) multiple different versions of curation.

**Comment by kazukisan** [comment]
I began migrating some codes to use v2.
I may have more feedback on this in the near future, but I noticed that Delete Document does not work yet:

When I looked at Swagger page, it says:
```DELETE /api/v2/projects/{projectId}/documents```

But I think it should be:
```DELETE /api/v2/projects/{projectId}/documents/{documentId}```
, because documentId is actually listed as a required parameter.

**Comment by reckart** [comment]
I'll be changing all responses to the form:

```
{
  "messages": [
    { "level": "debug|info|warn|error", "text": "some text"},
    ...
  ] 
  "body": XXX
}
```

where XXX is the result that the calls return at the moment.

**Comment by kazukisan** [comment]
Thanks for the comments and things are looking fine so far, at least to me.

For responses, will this still have 200 level when successful, and 400 or 500 level when not successful?

For ```document create parameter state - allow document to be created in a specified state```
what are document status to be set here? (Isn't document status determined more by if anybody annotated or if anybody began/finished curation?)

For 
``` project read - get project information ```
This API call accepts project ID in URL. But in the current implementation of V2 API, there isn't significant different between project read vs project list.
So, I think that there is an opportunity to do https://github.com/webanno/webanno/issues/425 by ```project read```, so that all the "read" calls (like documents, annotations, curations) are for exporting.

**Comment by reckart** [comment]
* wrt responses: yes, the error code will be the same as now.
* wrt document create something like: NEW, ANNOTATION-IN-PROGRESS, ANNOTATION-COMPLETE, CURATION-IN-PROGRESS, CURATION-COMPLETE
* wrt to project export: I was thinking of using a dedicate URL pattern for export: `/projects/{projectId}/export.zip`

**Comment by kazukisan** [comment]
The list of documents status looks great!

For ```document create```, it is assumed to be a new file to be imported into the project, correct? Is it reasonable to be able to set the status ANNOTATION-COMPLETE for a new file, even if nobody has annotated that new document yet? Wouldn't document create always have to end up with NEW status in the end anyway? While document create with state for ```annotations``` and ```curations``` is something good to have in the config, I wasn't sure about document create with status for new documents.

For project export, thanks!
```/projects/{projectId}/export.zip``` or maybe something like ```/projects/{projectId}/export?format=zip``` but the pattern looks good!

**Comment by reckart** [comment]
* wrt `document create`: hm, I simply considered adding the state parameter to `document create` to be aligned with `annotation create`. You are right, probably anything but `NEW` doesn't make sense here. So let's drop that parameter again?
* wrt `/projects/{projectId}/export.zip`:  I suggested that because even commands like "curl" then automatically use a reasonable file name. Something like `export?format=xxx` is more generic, but it requires the client to manually assign a sensible filename. Also, I don't think it is necessary at the moment to support anything but ZIP for the export. Mind, we are talking about a full-project export, not an annotation export.

**Comment by kazukisan** [comment]
For ```document create```, the status parameter can be dropped, I agree. And yes, I am also a fan of consistent design, but it's just that I felt it would always need to be "New" status anyway. (because of the consistent format looked great, I actually didn't think of this until some time ago)

And project.zip sounds good, as long as the only supported format for now is zip.

Thanks for response once again.

**Comment by reckart** [comment]
@kazukisan btw. do you have any idea/preference regarding PUT vs. POST e.g. when importing annotations?

**Comment by reckart** [comment]
... and whether e.g. "format" and "state" should be URL or multi-part form parameters?

**Comment by kazukisan** [comment]
For ```annotations create```, I believe what it does is to create annotation for a specified user name, if an annotation for that user name does not exist yet, otherwise it overwrites the current annotation of that user? If so, PUT seems semantically more appropriate, after reading this: https://knpuniversity.com/screencast/rest/put-versus-post
What do you think? (No strong preference on my end)

For format / state parameters, I am not sure which is considered the best practice between URL or multi-part body. I am not sure if there is an answer to this. But I think that using URL for all endpoints, except binary data, could be considered consistent.

Now that PUT vs POST has been mentioned, I also thought of PATCH, for example, changing the document state of annotation or curation, without having to re-upload the file.
Although it is an additional item, implementing PATCH endpoints (for parameters like ```state```) for annotations/curations, I feel, should be able to satisfy this request: https://github.com/webanno/webanno/issues/412

**Comment by reckart** [comment]
@kazukisan if you use the new remote API, you will have to update you client code after the latest change as [the "messages" feature](https://github.com/webanno/webanno/issues/455#issuecomment-283011969) has now been implemented.

**Comment by kazukisan** [comment]
Great!!
Thanks for the info, and I will test things out tomorrow here in USA Eastern time.

There is Python API wrapper that I implemented in my team, and I am hoping to share that at some point if it can get through legal.

**Comment by reckart** [comment]
I am implementing the deletion of annotations such that the annotation metadata recorded in the database is removed and the latest annotation file on disk. If WebAnno is configured to keep an internal set of backups, these backups remain.

**Comment by reckart** [comment]
@kazukisan I am implementing the upload of a curation such that it will always update the state of the associated document into CURATION-IN-PROGRESS or (optionally) CURATION-COMPLETE.

**Comment by reckart** [comment]
@kazukisan I think this is all done now, although I have to admit that I didn't really test everything. I'm going to do a new beta release now. If you find the time to test, would be great.

**Comment by reckart** [comment]
@kazukisan project import and export via ZIP files should now work.

**Comment by kazukisan** [comment]
Annotation state / Curation state are checked in this JIRA issue, but it doesn't look like it has been implemented, at least when I look at swagger-ui.html page.

**Comment by reckart** [comment]
The annotation state is returned along with the listing the annotations and the document/curation state is included in the listing of documents - therefore I didn't implement a call to query the state of a single source/annotation document. Is it enough to have the states in the list results?

**Comment by kazukisan** [comment]
Sorry I didn't specify in the comment but I meant the annotation / curation state during creation (POST), which are checked in the top description but didn't see in swagger.

**Comment by reckart** [comment]
Hm, you are right, it doesn't show up in swagger... but the parameter is in the code:

https://github.com/webanno/webanno/blob/9515467125f42b0d83f98f4aca6183c40aff1de0/webanno-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController2.java#L479-L491

I guess Swagger may have a problem with the `Optional` here...?

**Comment by kazukisan** [comment]
Thanks for looking in, and yes, it is weird on swagger's end but at least it is noted here.

**Comment by reckart** [comment]
Ok, fixed: https://github.com/webanno/webanno/issues/694

**Comment by kazukisan** [comment]
For remote API, one thing I am looking into is to be able to change annotation status of bunch of documents (200 - 300) of a particular user, for example. But no change in the actual annotation of the document. Would it make sense to make filename parameter optional for such a call? 

(Trying to resort API-based annotation doc status change because monitoring gets very slow if the projects contain like 1000 docs, and aware of issue #90

**Comment by reckart** [comment]
I would tend towards introducing a special "update" call for such a purpose, maybe via the "HTTP PATCH" method. Let's open a new issue improvements in the remote API in 3.4.0.

**Comment by nipunsadvilkar** [comment]
I am unable to get API `Status - 200` response with even simple `GET /api/v2/projects` request. Getting `Forbidden - 403` error every time through swagger-ui.html though I have logged in with **admin** user of webanno.

Am I missing something? I am not able to get much documentation specific to API. 
Little help would be highly appreciated. Thanks!

I am using `webanno-standalone-3.4.8.jar`

**Comment by nipunsadvilkar** [comment]
Thank you so much for the response. it's working! 👍
