### ISSUE TITLE
Filtering Functionality + Clarin Logo and HelpDesk Button

### ISSUE THREAD

**Issue by bencampbell30** [webanno/webanno#501]
I'm a research assistant at the University of Tübingen working with a local version of WebAnno. I have developed functionality that allows users to filter the list of users that can be added to a project. As well, I have added a Clarin HelpDesk button and the Clarin logo to the page header dependent on the settings file, ie. the code checks for the properties "clarin.logo.address" and "clarin.website" for the Clarin logo, and "helpdesk.logo.address" and "helpdesk.website" for the HelpDesk button. If these are not present, then the HelpDesk button or Clarin logo simply does not show up and the user doesn't notice anything. Would it be possible to have this functionality integrated into the next release of WebAnno?

**Comment by reckart** [comment]
It would be great to get a pull request regarding the changes for the users being added to a project.

You could provide a separate pull request regarding the additions of the links to get an idea of how what you are trying to do and how you did it. However, that PR would most likely not get accepted in favor of an alternative more generic solution, e.g. one that allows to customize certain parts of the UI.

WebAnno has recently see a lot of changes to make it more modular, extensible, and customizable. Because this is still ongoing, the WebAnno codebase is presently very much in flux. However, eventually you might want to consider creating a "branded" version of WebAnno similar to the one [here](https://github.com/openminted/omtd-annotation-editor).

**Comment by reckart** [comment]
Addressed via #516 and #509.
