### ISSUE TITLE
Modularization of feature support

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#524]
Support new types of features on annotations and respective editors through an extension mechanism.

**Comment by reckart** [comment]
@astier this might be interesting for you.

**Comment by astier** [comment]
I managed now to load tags dynamically based on certain criteria when I select a span. However, I am using for this not _dynamic features_ but _dynamic tagsets_.

Basically I define a tagset which is supposed to load tags dynamically and assign it to a feature. When selecting a span in the annotation-mode the program looks if the tagsets which are loaded by the ADEP are marked as dynamic. If so then instead of loading the respective tags from the database with _annotationService.listTags(tagSet)_ I load them by using an Interface which returns a list of tags. I am working on it right now in my fork on the branch [feature-1.2/dynamic_tag_loader](https://github.com/astier/webanno/tree/feature-1.2/dynamic_tag_loader).

This was so far the easiest solution without must having to change to much of your code.

**Comment by reckart** [comment]
As usual there are multiple way of approaching this. Yours seems to kick in when loading tags into the existing string feature editor. In the mid-term, I am thinking of a more generic extension to the feature system which would allows plugins to provide their own feature types coupled with own feature editors. Let's just keep an eye on each other. We're working at different speeds and with different ideas - let's see if/where we might meet.
