### ISSUE TITLE
adaptive coloring strategy

### ISSUE THREAD

**Issue by remstef** [webanno/webanno#531]
refactor selection of coloring strategy, and make it independent of "readonly" option

E.g. would the following mockup be an option?

![adaptive colering strategy](https://user-images.githubusercontent.com/5611665/27218209-75b40cca-527d-11e7-8e01-8f078330246e.png)

**Comment by reckart** [comment]
Hm... IMHO visibility and coloring are orthogonal. I.e. when I "unhide" a layer, it should IMHO show again using the previously configured coloring scheme.

What made you consider the per-layer coloring again? I though last time we talked, we had gravitated towards having options in the lower part like:

- Use the same color for all tags in a layer y/n
- Colorize non-editable annotations y/n

**Comment by remstef** [comment]
>  when I "unhide" a layer, it should IMHO show again using the previously configured coloring scheme

that's a fair point, I agree to that 

I think we need that in a way configurable per layer, we are restricting ourselves too much if its a global option. E.g. unchecking the "Use the same color for all tags" might make sense when working with specific tagsets like POS tags, but it does not really make sense when using free text. Another possibility is to put that kind of option into the layer configuration in the project page, only admins can then change it, in order not to overwhelm the user. What's your take on that?

**Comment by reckart** [comment]
Since different users perceive colors differently, I think it makes more sense to have color-related settings close to the user - not close to the admin.

Ok, so let's say we make the label-based or layer-based coloring strategy something that can be configured per layer - a dropdown would seem useful for that.

To me the question whether a read-only layer should be greyed out or not seems kind of independent of the chosen strategy though. That is, I tend towards believing that if a user wants read-only layers to be colored, it should apply to all read-only layers - likewise if the user wants them to be monochrome or possibly even transparent.

What do you think about allowing to configure the coloring-strategy via  dropdown per layer and having another global dropdown labeled "Colorize read-only layers" with the options "normal" and "gray-scale"?

**Comment by remstef** [comment]
That sounds good to me.

**Comment by remstef** [comment]
I'm wondering where to store the preferred coloring strategy. On the one hand it is similar `AnnotationPreference.isStaticColor`, but on the other hand it is similar to `AnnotationLayer.isEnabled` and a list of `AnnotationLayer` objects is also stored in `AnnotationPreference`. @reckart do you have an opinion?

**Comment by reckart** [comment]
Since the preference is per-user, it has to be stored in AnnotationPreference.

**Comment by remstef** [comment]
but the `AnnotationLayer.isEnabled` is also per user, isn't it?

**Comment by reckart** [comment]
The project manager can centrally disable layers for the whole project - this is `AnnotationLayer.isEnabled()`.

A user can individually hide/show layers in the annotation editor preferences. This is `AnnotationPreference.getAnnotationLayers()`

**Comment by reckart** [comment]
To implement these you preferences, it probably makes sense to also refactor the way that layer visibility is stored in `AnnotationPreference`. I think it would be ok to do that in a breaking way, i.e. in such a way that users may loose their **per-user** visibility/coloring preferences and have to re-configure them again after upgrading WebAnno. We should mention that in the release notes.

**Comment by remstef** [comment]
alright, I'll see to that

**Comment by remstef** [comment]
Funny, there is a method `AnnotationPreference.getAnnotationLayers` but apparently its never used except in `PreferencesUtil.loadPreferences`

**Comment by remstef** [comment]
i mean `public List<Long> getAnnotationLayers()`

**Comment by reckart** [comment]
I'm afraid the way that the per-user annotation preferences are stored is kind of twisted. It could probably be done in a much more straight-forward way using Jackson. Not sure how much care needs to be taken though. E.g. a thing that was causing some problems in the past was: 
* What happens when new layers are added by the project manager? Should the be visible or hidden by default?
* What happens if a user sets all layers to hidden? vs What happens if a user opens a document with no visibility preferences set? - I.e. should all layers be set to visible then?

**Comment by reckart** [comment]
`PreferencesUtil.loadPreferences` is using the reflection API.

**Comment by remstef** [comment]
Bug: selecting and deselecting layers is not working properly.

**Comment by reckart** [comment]
Hm, so are we done here?

**Comment by remstef** [comment]
Yes, I'd say so :)
