### ISSUE TITLE
Agreement report sometimes contains positions where both annotators have a "null"

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#55]
Agreement report sometimes contains positions where both annotators have a "null". I assume this happens when one or both annotators created an annotation, but they did not assign a label to the feature over with agreement is calculated. E.g. one or both created a "Lemma" annotation and did not set the "value" feature.

It should be checked if this is assumption is correct.

**Question:** Does it make sense to keep such positions if "exclude incomplete" is disabled or whether they should be completely dropped from the agreement report.

**Comment by mmeva** [comment]
The problem is still not managed in WebAnno -- 3.0.0-beta-2.

A proposal:
1) Not labeled, but annotated instances should be counted as annotated instances with a *non-null* label, maybe an empty label would be appropriate (if technically ok). Thus, an annotated instance on a particular offset with an empty label could be distinguished from a missing instance on this offset.
2) Or: An *additional* possibility of comparing *only the offsets* for matching could be provided.

Notes on the proposal with a case that we measure the IAA between annotators A and B on Layer L with Feature f.
Ad 1):
Now, there is no difference in the agreement output file between two cases:
a) Annotator A has annotated an instance of L on offset m-n, without setting a value for f.
b) Annotator B has not annotated any instance of L on offset m-n at all.
The output agreement file entails in both cases an item with the value null.

Ad 2):
In this case only the offset-matches are interesting for the agreement calculation.
If there is no annotation on offset m-n by one of the annotators (case 1/b) above), then it could be counted as a missing/incomplete annotation. 

What do you think?

**Comment by reckart** [comment]
If I remember correctly, the "annotation study" which is the data structure derived from the annotated data and given to DKPro Statistics does not have a concept of offsets, only of labels (at least as long as we are not using unitizing measures).

So I would go with option 1), basically that a "null" value is interpreted as an empty label. That is, instead of adding a "null" value to the study, I'd add simply add an empty label. It could then still happen that both annotators have an empty label.

So we would end up with three possibilities:

* `null` - there is no annotation at this position
* `<empty>` - there is an annotation but it does not have a label (I would actually use the empty string here, not `<empty>`)
* `<label>` - if there is an annotation and the feature has a label

**Comment by reckart** [comment]
Annotations with `null` feature values are now considered to have an empty feature value. They are also considered to be proper labels.
