### ISSUE TITLE
Some export formats seem not to work properly

### ISSUE THREAD

**Issue by astier** [webanno/webanno#602]
I annotated a document with different features (Lemma, POS, Chunk, Named Entity single, Named Entity stacked). When I try to export the document with different formats I get the following issues:

1. _CoNLL 2000_, _CoNLL 2002_ and _Plain-Text_ do not show any annotated feature values.
2. _CoNLL 2006_ and _CoNLL-U_ show only Lemma and POS. However POS is declared twice in the
    exported file although I annotated it only once.
3. _CoNLL 2009_ shows only Lemma and POS. However, POS and Lemma are declared twice in the
    exported file although I annotated them only once.
4. Only _WebAnno TSV 3.1_ seem to work properly.

This is based on _WebAnno 3.3.0-SNAPSHOT_ commit e5ad6b6f8323026db7c1260d696f983de01c041b.

**Comment by reckart** [comment]
The CoNLL formats do not show custom layers and the only show specific built-in layers depending on which year year is used (2000, 2006, 2009, etc.). These are fixed formats. You can check out their definitions here: https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/format-reference.html#format-de.tudarmstadt.ukp.dkpro.core.io.conll-asl

So what you are seeing is the expected behavior. No bug ;)

**Comment by astier** [comment]
Ok. Thanks.
