### ISSUE TITLE
UIMA CAS JSON import document

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#652]
There is JSON CAS writer, but reader doesn't look like implemented in WebAnno yet.

**Comment by reckart** [comment]
The writer is based on the JSON CAS serializer from the UIMA SDK. Unfortunately, the UIMA SDK does not yet offer a reader for this format. Contributions of a JSON CAS deserializer to the UIMA SDK surely would be welcome.

**Comment by obradovicma** [comment]
Hi, we are currently working on an NLP project in medical context. We are using UIMA JSON files for annotation and we would really appreciate a UIMA JSON reader/importer. Currently, we are thinking of writing something like a UIMA JSON-XMI converter in Python in order to be able to import the automatically prelabeled data into webanno.
Is there maybe a alpha or beta version of the UIMA JSON importer we could try out? Would be great since we cannot wait for webanno 3.6.0. Thanks in advance!

**Comment by reckart** [comment]
As far as I know, the UIMA project only provides a writer for their particular CAS JSON format, but so far nobody has implemented a reader for this format. Contributions are surely welcome. You might try asking on the UIMA mailing list if anybody has something unpublished sitting around somewhere.

Mind 3.6.0 is basically just a placeholder for "not in the next release" (which is 3.5.0). This issue will most likely be deferred until somebody has implemented/contributed a CAS JSON reader to the UIMA project from where we would then pick it up.

**Comment by obradovicma** [comment]
Thanks for your very quick response! I will discuss the issue with my team mates and then contact you again. Thanks again!

**Comment by reckart** [comment]
The JSON format currently provided by UIMA is not parseable back into a CAS - it is a one-way transformation. The reason is primarily that information about annotation type names is lost during serialization. It would be necessary to define another JSON format for the CAS data which contains sufficient information for reading all data back in.

**Comment by GiantEnemyCrab** [comment]
Thank you for checking!
