### ISSUE TITLE
Relation annotation deleted without warning

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#662]
If relation annotation is not allowed "stacking" and a new arc is drawn on an existing relation annotation, it removes the existing  relation values and create an empty new relation value
Version: 3.3.0-SNAPSHOT
Browser: chrome
Relation layer: Dependency

**Comment by reckart** [comment]
Just to make sure what is desired. I'm just looking at the code from WebAnno 3.2.x and that says:

```
// If stacking is not allowed and we would be creating a duplicate arc, then instead
// update the label of the existing arc
```

Personally, I think an error message

**Comment by reckart** [comment]
Thinking of it, the behavior that you describe is consistent with the comment in the code. I assume this comment still comes from the time where we had the annotation dialog. So when a user created a new dependency relation at the same place as another one and stacking was not enabled, then the old relation was replaced with the new relation. And since we were using a dialog, the label of the relation was usually set before the dialog was closed.

The difference today is, that we do not have the dialog anymore. So just the relation is created without a label.

**Comment by reckart** [comment]
I am generating an error message now along the lines what we do for span layers as well. I hope you agree that this is the correct solution.
