### ISSUE TITLE
Cannot load documents on the latest beta version

### ISSUE THREAD

**Issue by Jona3007** [webanno/webanno#666]
Hi, I am trying to load .txt documents on WebAnno ver. 3.3.0 beta 4 and I get this message 

> Error analyzing CAS of user [admin] in document [humans.txt] (2) in project[Annotation Of Mobility] (2); nested exception is javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement_

could you guide me on what to do?

Thank you!
Jonathan

**Comment by reckart** [comment]
Are you using MySQL?

**Comment by Jona3007** [comment]
No I am not

**Comment by Jona3007** [comment]
I just use a text file

**Comment by reckart** [comment]
Are you using the standalone JAR version of WebAnno?

**Comment by Jona3007** [comment]
Hi, yes I am using the standalone JAR version

**Comment by reckart** [comment]
I need to see if I can reproduce this locally.

**Comment by reckart** [comment]
I just ran webanno-3.3.0-beta-4 locally with a fresh/empty webanno home directory and imported a simple text file as "plain text" and that worked just nice.

What Java version are you using?

Could you try creating a new empty directly and then start WebAnno using (replacing `/path/to/your/empty/directory` with the actual path of the empty directory you just created)?

```
java -Dwebanno.home=/path/to/your/empty/directory -jar webanno-standalone-3.3.0-beta-4.jar
```

and then re-try importing the document? 

If it still fails, can you provide a stack trace?

**Comment by reckart** [comment]
I think we may have a problem that Hibernate does not properly upgrade an existing embedded database with new columns. Need to check this in more detail.

**Comment by reckart** [comment]
Looks like the columns are correctly generated. At one point, we had a situation between snapshot builds and betas that some new columns were created as not-nullable and some were renamed. This could lead to a situation where a row would be created with a non-null column being null (mind that Hibernate doesn't drop columns and doesn't remove non-null constraints either). However, that was a temporary situation and should not affect users that switch from 3.2.x to 3.3.0.

So, l think this issue is not a problem and can be closed.
