### ISSUE TITLE
Unexpected data discrepancy in curation mode

### ISSUE THREAD

**Issue by SJones-Appen** [webanno/webanno#683]
Envr: Webanno 3.2.1 / Windows 8.1 / Chrome 61.0.3163.100

We're observing unexpected differences between an annotated file and the corresponding unmodified curator file in curation mode. 

Attaching the two files where the problem is observed, CURATION_USER.tsv and annotator.tsv

No changes were made in the curation panel; the file was simply marked Finished and exported. A diff report of the two exported files is attached as report.html.

Screengrab of the annotator's work in Curation mode is attached as anno.jpg. View of unchanged data in curation panel is attached as curation.jpg. Unexpected system message attached as message.jpg

[3.2.1_display_problem.zip](https://github.com/webanno/webanno/files/1403230/3.2.1_display_problem.zip)

**Comment by reckart** [comment]
The message under "invisible annotations in other pages" indicates that a relation is not being shown because its begin or end point are outside the current set of visible sentences (i.e. the current page).

The diff you observe between the CURATION_USER and the annotator user should be explainable in the following way: when a curator opens a document for the first time in the curation panel, then WebAnno compares the annotation of all annotators with each other. All annotations that *all* annotators agree upon (i.e. same annotation at exactly the same span) are merged automatically into the upper part (i.e. the CURATION_USER). All other annotations remain unmerged and must be manually inspected by the curator. Clicking on an annotation in one of the lower panels (i.e. those showing the annotator names) merges the selected annotation into the upper part.

If the curator opened a document in the curation panel before all annotators have completed their work (e.g. for curiosity), then the curator may have to use the "re-merge" button in the toolbar to discard the current data for the CURATION_USER and to re-generate it from the annotators data.

Does that explain what you are seeing?

**Comment by SJones-Appen** [comment]
Thank you! Your detailed explanations took care of everything.
