### ISSUE TITLE
Installing Webanno on a Debian virtual machine

### ISSUE THREAD

**Issue by Jona3007** [webanno/webanno#702]
Good morning, a friend asked me to pass along this question to you: 
"I followed the administrator instruction to install Webanno on a Debian virtual machine, but the final webpage “http://localhost:18080/webanno” displays a “blank” page. What would be wrong? All services run normally, including Apache Tomcat, MariaDB MySql, and Webanno service."
Any help is greatly appreciated.
Thank you,

**Comment by reckart** [comment]
* Which WebAnno version are you using?
* Does the tomcat log state that WebAnno has started?
* What is the name of the WAR file in the Tomcat webapps folder?

**Comment by Jona3007** [comment]
Instructions are taken from latest version: https://webanno.github.io/webanno/releases/3.2.4/docs/admin-guide.html . All installations are fresh on a dedicated Debian virtual machine.
•	WebAnno version 3.2.4
•	“service webanno status” showed “active”
•	WAR file “webanno.war”

Thank you,

**Comment by reckart** [comment]
Does the `catalina.out` log from Tomcat show any errors during startup?

**Comment by reckart** [comment]
I have tried installing WebAnno 3.3.0 on a fresh Debian 9.1 in a VM and have slightly updated the installation instructions for Debian 9 in the process: https://github.com/webanno/webanno/commit/ea47dafb6996d2bc417efb3fa7cd0522b58fd48b

Mind that I didn't try the part of running it behind Apache HTTPD yet.

Since there has been no further feedback on this issue, I assume it could be resolved or is no longer relevant. If not, please reopen.

**Comment by Jona3007** [comment]
Good morning, 

my friend asked me to reply this to your question about Tomcat showing any errors during startup.
"There are multiple errors and it seems like there is a permission issue, please ask if they could help figure out what causes the errors. thank you"
he also send this attachment, thank you for your time and help.
[catalina.out.txt](https://github.com/webanno/webanno/files/1547752/catalina.out.txt)

**Comment by reckart** [comment]
There are many problems in that log. I'll comment only on the last attempt to start WebAnno.

```
  _      __    __   ___                
 | | /| / /__ / /  / _ | ___  ___  ___ 
 | |/ |/ / -_) _ \/ __ |/ _ \/ _ \/ _ \
 |__/|__/\__/_.__/_/ |_/_//_/_//_/\___/
3.3.0 (2017-11-28 22:38:33, build 4130ba67d445d7a136b67a418a71073d7afb1f14)

2017-12-08 15:52:02 INFO [SYSTEM] WebAnnoApplicationContextInitializer - Settings: /srv/webanno/settings.properties
<snip>
2017-12-08 15:52:15 INFO [SYSTEM] DocumentServiceImpl - Database dialect: org.hibernate.dialect.HSQLDialect
2017-12-08 15:52:15 INFO [SYSTEM] DocumentServiceImpl - Database driver: com.mysql.jdbc.Driver
2017-12-08 15:52:15 INFO [SYSTEM] DocumentServiceImpl - Database URL: jdbc:mysql://localhost:3306/webanno
2017-12-08 15:52:15 INFO [SYSTEM] DocumentServiceImpl - Database username: webanno
```

This looks like the line `database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect` is missing from the `/srv/webanno/settings.properties` file because apparently WebAnno tries to talk to MySQL using a HSQLDialect - which won't work.

**Comment by Jona3007** [comment]
Thank you! I will pass this answer along

**Comment by reckart** [comment]
Mind that previous attempts to start WebAnno failed e.g. because the database user specified in `settings.properties` did not exist or did not have sufficient privileges or because some other process was already running on the Tomcat port. So if it could be that if you fix the `settings.properties`, another problem will come back.
