### ISSUE TITLE
Support morphological features from CoNLL formats

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#708]
Support morphological features from CoNLL formats

**Comment by reckart** [comment]
@normundsg @hahmyg I am considering adding a default "Morphological features" layer for better support of importing/exporting CoNLL/CoNLL-U formats with morphological information. It can easily be done by treating the morphological features as a single String field. However, it results in a quite longish label in the UI (see screenshot).

![2017-11-16_14-31-26](https://user-images.githubusercontent.com/1410238/32893884-612c7ce8-cadb-11e7-9dff-8abccec51be4.png)

Would this be useful for people caring about doing morphological annotations? Or better leave it out until a better support for editing the different "subfields" of the morphological features could be edited independently in the UI?

**Comment by normundsg** [comment]
I vote for leaving it out until a better support for editing feature structures. Labels would get even longer for highly inflected languages. However, it would be useful to include morphological features in the POS info boxes (on mouse over POS labels).

On the other hand, if the new layer can be hidden this can be a temporal solution.

P.S. For Latvian, we actually do not use WebAnno to annotate morphology and syntax, since our syntactic model is too complex for WebAnno. Instead we still use Tred. Then we automatically transform trees from our hybrid dependency-constituency model to UD. The CoNLL-U files are then imported in WebAnno to annotate higher layers: FrameNet, named entities, and coreferences (still experimenting with corefs due to entity linking etc. issues).

**Comment by reckart** [comment]
Thank you for the feedback.

Based on your response, I think it would be worth at least adding the layer but disabling it by default - so who would want to use it would have to explicitly enable it.

The second option could be to enable the layer by default, but not to show any values in the label (only e.g. `Morph`) and show the values only on-mouse-over. That would probably also not be difficult to do.

**Comment by reckart** [comment]
![2017-11-19_11-01-12](https://user-images.githubusercontent.com/1410238/32989559-08b1b962-cd19-11e7-98cb-7b20b1235c83.png)

I have added a built-in layer for morphological features which is disabled by default and when enabled by default shows only in the mouse-hover popup.
