### ISSUE TITLE
no highlight over an agreed sentence on the monitoring panel

### ISSUE THREAD

**Issue by dicleoztur** [webanno/webanno#73]
there is no highlight over a text which received the same label from both (or more maybe) annotators during the curation process. such cases can be coloured differently and prevents skipping upon further analysis.

**Comment by reckart** [comment]
Over which text do you expect a highlight to be shown?

**Comment by dicleoztur** [comment]
attached is the screenshot.
on the left bar, the sentence should have been coloured because it has been
labelled but not.

On 6 August 2015 at 16:48, Richard Eckart de Castilho <
notifications@github.com> wrote:

> Over which text do you expect a highlight to be shown?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webanno/webanno/issues/73#issuecomment-128400429>.
>



-- 
Dicle

**Comment by reckart** [comment]
It looks like Github doesn't support screenshots in mail attachments. You can drag-and-drop images into the issue editor on the website.

**Comment by reckart** [comment]
If the two annotators they agree, then the labels/highlights are colored in gray and the annotation is automatically transferred up into the "annotation" area.

Would they not agree, they would be blue and the annotation would not be copied up automatically.

If the curator accepts either of the two as correct, it turns green and is copied up. The one from the other annotator then turns red.

What should in your opinion be changed here?

**Comment by reckart** [comment]
I've had a chance to talk with Dicle.

So this issue is about the highlighting of sentences in the *sentence overview* (left). Currently, we only highlight sentences with disagreements there. The request is to make a distinction between three cases in the sentence overview:

* disagreement (e.g. red)
* agreement (e.g. green)
* no annotations at all (e.g. white)

As a comment on this though: currently the overview highlighting depends on the agreement between annotators - it does not take curation into account. Thus, there is no change in highlighting when a sentence has been curated. Some users have suggested that it would be more convenient if the highlighting was based on whether curation for a sentence was completed or not - such that the highlighting would indicate which sentences are still "todo".

**Comment by reckart** [comment]
This should be addressed now in INCEpTION: https://github.com/inception-project/inception/issues/2193
