### ISSUE TITLE
Emojis get corrupted on TSV export

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#746]
For example, we imported:

```
#Text=\uF60A                                                                                                                                                                     
39-1    2364-2365       😊 
```

And WA exported:

```
#Text=\uF60A
39-1    2364-2365              _
```

**Comment by reckart** [comment]
Which version of WebAnno are you using?

**Comment by cyplas** [comment]
3.2.2 (2017-07-18 23:57:48, build 61cea1f0f7eda3b57d7c548d0577f166ac2830ce)

**Comment by reckart** [comment]
Could you try importing the project into a WebAnno 3.3.0 and exporting it form there as TSV? The TSV support in WebAnno 3.3.0 has been rewritten from scratch. If fixes need to be done, I'd do them there rather than in deprecated code.

**Comment by reckart** [comment]
@cyplas I set up a TSV unit test (based on the new implementation). Based on that, I believe that the data you imported is broken. 😊 seems to be a character that cannot be represented in 16 bit (UTF-16). The code seems to be `U+1F60A` while in your example, only the lower 16 bit `\uF60A` seem to be used. Looks like the offsets here should be going from 2364-2366 (not 2355).

Here an excerpt of a TSV3 file with this emoji:

```
#Text=I like it 😊 .
1-1	0-1	I	_	
1-2	2-6	like	_	
1-3	7-9	it	_	
1-4	10-12	😊	*	
1-5	13-14	.	_	
```

Note the offsets of token `1-4`, which cover two "characters".

**Comment by reckart** [comment]
The old (3.2.x) TSV implementation also seems to be fine if the offsets for the emoji are two characters wide. I.e. the snippet above can be read/written properly by the legacy TSV implementation.

**Comment by cyplas** [comment]
Thanks for looking into this and your feedback. If I understand you right (which isn't clear, whenever character encodings are concerned), the TSV3 offset column is based on pairs of UTF-16 bytes? So if a token was, say, "wow😊", then the length would be considered (2 + 2 + 2 + 4) / 2 = 5? Why is the offset based on UTF-16? I can't find a reference to UTF-16 in your wiki. :) This is very relevant for us, because we convert from a local XML format to TSV3.

**Comment by reckart** [comment]
It is indeed a bit confusing ;)

The offsets are based on the Java-internal representation of strings [1]. Java internally uses UTF16 for string representations. A character in Java is 16bit wide. If a Unicode character cannot be encoded in 16bit, a second 16bit Java character is being used according to the UTF16 specs. The offsets we use are determined based on the Java String representation. Because not all Unicode characters can be encoded as a single Java character, there is a difference between "(Java) character offsets" and "(Unicode) codepoint offsets":

```
"wow😊".lenght() = 5
"wow😊".codePointCount(0,5) = 4
```

Here you can see what happens if we access this string by character offsets:

```
"wow😊".substring(0,3) = "wow"
"wow😊".substring(0,4) = "wow?" // the ? here is likely a fallback symbol for an invalid Unicode character
"wow😊".substring(0,5) = "wow😊"
```

You are right, this behavior is not documented. We didn't really hit the issue before. For the moment, I think it we should really document this behavior. 

I wonder if it would be worth changing this behavior for further TSV versions in order to use codepoint offsets instead of (Java) character offsets. Most likely, it would make the code quite a bit more complex and slower since codepoints are not random-access... having some doubts here...

[1] http://www.oracle.com/us/technologies/java/supplementary-142654.html

**Comment by cyplas** [comment]
Aha, thanks for the explanation. As we are dealing with social media corpora, this is an annoying issue for us. But I understand your technical concerns as well ... So If I understand right, we'll need to deal with this locally, at least for now.

Hmm, the offset column is mandatory in TSV3, right? Even if we're not using features that are based on it (AFAIK)?

**Comment by reckart** [comment]
For token-level annotations, it might be possible to change the code to ignore the offsets and trying to infer the token position from the token text - it would make the code more complex and more fragile. For sub-token annotations there is hardly a way around offsets.

**Comment by cyplas** [comment]
I see, it is indeed a messy business.

It seems that all I can reasonably request in the short term is that you document this and have a further think about a long term solution. In the meantime, we'll just dream of (you or us) finding a way to address this cleanly and efficiently. :)

**Comment by reckart** [comment]
How do you convert your XML files to TSV3? I guess if you could write that code in Java, it would solve your problem.

**Comment by cyplas** [comment]
We use perl and XSL, but hmm, thanks for the idea.

**Comment by reckart** [comment]
If you prefer scripting languages, Groovy should work as well. It is a JVM-based language and has good support for handling XML (http://groovy-lang.org/processing-xml.html).

**Comment by reckart** [comment]
The behavior is now documented.
