### ISSUE TITLE
No reader available for format [TAB-SEP]

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#753]
Automation failed with an exception `java.io.IOException: No reader available for format [TAB-SEP]`

TAB-SEP training files should be managed separately than other file formats

**Comment by reckart** [comment]
@seyyaw please remember to follow the commit message format. Since you are not committing regularly anymore and since there tend to be problems with the commit messages, may I suggest you do pull requests instead of directly committing to master and let me review and merge the changes (and in case necessary fix the commit messages)?
