### ISSUE TITLE
Configuring a default annotation layer

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#771]
I have a project with three annotation layers: FE, Frame, and LU.
![default](https://user-images.githubusercontent.com/1726922/33889076-b6a5c090-df57-11e7-88bd-2b57180f5f83.png)
In the Annotation view (and Curation view), LU has become the default layer (perhaps because it was the last one added and/or due to the A-Z order). My annotators are quite annoyed about this, since Frame should be the default one.

Usability **suggestion**: a possibility to specify the default annotation layer (e.g., in the user settings dialog).

**Comment by reckart** [comment]
I think the layers are sorted alphabetically. As a workaround, you could probably rename the layers in the project settings and e.g. prefix them with numbers. However, when creating layers, I would recommend first creating them with the regular name (in order to set the "internal name" which is based on the name at creation time) and then rename them afterwards.

That said: having this as a user preference (or maybe simply remembering the last layer selected even across editing sessions?) sounds like a good improvement.

**Comment by normundsg** [comment]
The workaround works, thanks!

Looking forward to 3.4.0 :)
