### ISSUE TITLE
Mouseover behavior for curation mode when selecting tags

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#817]
In Annotation mode, there are selection box(es) on the right side to select the tag. When mouseover the selection box's tag entry, it shows a tooltip on the bottom middle. This is great!

Curation mode has the same set of selection box(es) as the annotation, but when doing mouseover, it doesn't show the tooltip, so consistency would be nice.

I didn't test automation mode...

**Comment by reckart** [comment]
Interestingly the tooltip comes back when the user reloads the page (F5).

**Comment by reckart** [comment]
Might be related to a clash between JQuery UI and Bootstrap (cf BootstrapAwareJQueryUIJavaScriptResourceReference).

**Comment by reckart** [comment]
The problem seems to occur only when a document is opened through the "open" dialog / when the page is opened for the first time. 

Once an annotation has been edited via a TextFeatureEditor with a tagset containing tooltips, the tooltips show ok. Also re-loading the page after a document has been opened makes the tooltips appear.

Needs further investigation.

**Comment by reckart** [comment]
#901 should fix this one as well.
