### ISSUE TITLE
"+" character in path causes crash

### ISSUE THREAD

**Issue by mujdricza** [webanno/webanno#884]
Issue:
The GUI cannot be opened, if the path to the standalone jar file contains a "+" character. 

tested 
- with 3.3.3 and 3.3.4 standalone released versions
- starting WA on command line or just clicking on the jar file
- opening the interface in Safari and Firefox 

See the attached console output.
[WA_3.3.4_plussigncauseserror_20180308-Safari.txt](https://github.com/webanno/webanno/files/1797037/WA_3.3.4_plussigncauseserror_20180308-Safari.txt)

**Comment by reckart** [comment]
@mmev thanks for reporting this. Looking at the error output, I believe there is not much we can do about it because the problem seems to happen entirely within third-party code, specifically within the LESS resource and LESS compiler. When I have time, I'll try to see to which upstream project the issue needs to be reported.
