### ISSUE TITLE
Annotations on document level

### ISSUE THREAD

**Issue by mariananeves** [webanno/webanno#923]
It would be great if the tool allowed annotation on document level (according to pre-defined classes or even an ontology) for text classification purposes. I guess that currently it is only possible by annotating a text span. But it complicates an annotation task which should be left simple.

**Comment by kazukisan** [comment]
It is nice to see that this is requested.

I did file a similar issue: https://github.com/webanno/webanno/issues/379

For now, I think that an alternative may be to use zero-width annotation at the very beginning of the document, by holding shift and release mouse on non-character region rather than annotating the entire span of the text and result in a lot of noise to the page.

**Comment by reckart** [comment]
This has been implemented in INCEpTION: https://inception-project.github.io/releases/0.17.4/docs/user-guide.html#_document_metadata
