### ISSUE TITLE
Different documents for different annotators

### ISSUE THREAD

**Issue by jrouces** [webanno/webanno#929]
Hi,

In the project I am creating, different documents are allocated to different annotators, although some subset of documents should be annotated by all of them to obtain inter-annotator agreements.
Creating copies of projects seems a source of redundancy and problems, so the best solution I find now is just including in the document names the annotator ids of those that should annotate them. but I wonder if there is a better way to manage this that I am currently missing. If there isn't, it could be a good feature to be included.

Best,
Jacobo.

**Comment by seyyaw** [comment]
Hi @jrouces 
If you do not know already, you can assign documents to annotators in the `Monitoring` page.

**Comment by jrouces** [comment]
Thanks @seyyaw, I had missed that. Is there some way to do that programmatically? I have documents in the hundreds or more, so it is an enormous amount of clicks. I have read about a programmatical API in here, but the manual only mentions it once and says "Currently experimental and undocumented. Do not use.".

**Comment by reckart** [comment]
@jrouces [INCEpTION](https://github.com/inception-project/inception) has a dynamic workload management mode since version 0.18.0 which can be used to model your scenario. At the start, one could use the default matrix-based workload management (aka monitoring page) so all annotators annotate all documents. The after the round is complete, you could import the remaining documents into the project and switch the project over to the new "dynamic workload management" where you just say "I want the documents to be annotated by X annotators" and the system dynamically assigns the documents to the annotators as they go along.
