### ISSUE TITLE
document state is ANNOTATION-IN-PROGRESS even after selecting FINISH ( in annotation workflow)

### ISSUE THREAD

**Issue by Anupam02** [webanno/webanno#965]
Hi, Just wanted to check for the flow / process states of documents gets changed for annotation.
I observed the following ,
 files in BLACK means its new , and its state is showing NEW as well from `api/v2/projects/<pro ID> /documents/<doc ID>/annotations/admin`
files in BLUE means its in progress , and its state is showing as ANNOTATION-IN-PROGRESS from `api/v2/projects/<pro ID> /documents/<doc ID>/annotations/admin` 

and in RED means its completed , but Its state is showing as ANNOTATION-IN-PROGRESS even after clicking on finish ( in annotation workflow).

I believe it should go to COMPLETE state once we click on FINISH , please correct me if I am wrong.

**Comment by reckart** [comment]
The annotation status is available via `GET /api/v2/projects/{projectId}/documents/{documentId}/annotations`.

I just did a test. Before pressing "FINISH" on the annotation page, I get:

```
{
  "messages": [],
  "body": [
    {
      "user": "admin",
      "state": "IN-PROGRESS",
      "timestamp": null
    }
  ]
}
```

and after pressing it, I get:

```
{
  "messages": [],
  "body": [
    {
      "user": "admin",
      "state": "COMPLETE",
      "timestamp": null
    }
  ]
}
```

That seems to work.

I `GET /api/v2/projects/{projectId}/documents`, the document indeed still reports to be in progress:

```
{
  "messages": [],
  "body": [
    {
      "id": 5020,
      "name": "test.txt",
      "state": "ANNOTATION-IN-PROGRESS"
    }
  ]
}
```

Why is that? Because the curation process was not started yet. Documents are not finished when the annotator presses "FINISH" but when the curator presses "FINISH". One the curator opens a document for curation, it transitions from "ANNOTATION-IN-PROGRESS" to "CURATION-IN-PROGRESS".

So everything should be working according to plan as far as I can see.

**Comment by Anupam02** [comment]
Thanks @reckart  , and when we finish the document curation,,
GET /api/v2/projects/{projectId}/documents would give CURATION-COMPLETE ,

 "state": "CURATION-COMPLETE"
    }


so the three possible states for GET /api/v2/projects/{projectId}/documents would be 
NEW, ANNOTATION-IN-PROGRESS and CURATION-COMPLETE right.

**Comment by reckart** [comment]
See 
https://github.com/webanno/webanno/blob/ee661681d858e1ea78340753d1f85361b189d8c9/webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocumentState.java#L25
